//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEDistributionStepViewController.h>

@class NSPopUpButton;

@interface IDEDistributionThinningStepViewController : IDEDistributionStepViewController
{
    int _thinningChoice;
    NSPopUpButton *_thinningOptionsPopUp;
}

+ (id)keyPathsForValuesAffectingEnableDeviceFamiliesPopup;
@property(retain, nonatomic) NSPopUpButton *thinningOptionsPopUp; // @synthesize thinningOptionsPopUp=_thinningOptionsPopUp;
@property(nonatomic) int thinningChoice; // @synthesize thinningChoice=_thinningChoice;
- (void)learnMore:(id)arg1;
- (BOOL)canGoNext;
- (id)nextButtonTitle;
- (id)title;
- (void)updateValueFromMenu:(id)arg1;
- (void)updateMenuWithFamilies:(id)arg1;
- (void)viewDidLoad;
@property(readonly) BOOL enableDeviceFamiliesPopup;

@end

