//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEDistributionStepViewController.h>

@class DVTReplacementView;

@interface IDEDistributionAppRecordStepViewController : IDEDistributionStepViewController
{
    DVTReplacementView *_replacementView;
}

@property(retain) DVTReplacementView *replacementView; // @synthesize replacementView=_replacementView;
- (void)selectAppRecord:(id)arg1;
- (void)_loadAppRecords;
- (void)_initializeStepWithReasonForPicker:(id)arg1;
- (void)viewDidInstall;
- (id)_installAndReturnProgressView;
- (id)title;
- (id)nibName;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;
- (void)primitiveInvalidate;

@end

