//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEDistributionOptionsSliceViewController.h>

@class NSArray, NSString;

@interface IDEODRHostDistributionOptionsSliceViewController : IDEDistributionOptionsSliceViewController
{
    NSArray *_manifestPaths;
    NSString *_inputValue;
    NSArray *_inputHistory;
}

+ (id)keyPathsForValuesAffectingCanGoNext;
@property(retain) NSArray *inputHistory; // @synthesize inputHistory=_inputHistory;
@property(retain) NSString *inputValue; // @synthesize inputValue=_inputValue;
@property(readonly) NSArray *manifestPaths; // @synthesize manifestPaths=_manifestPaths;
- (id)preferredTitle;
- (void)willGoNext;
- (BOOL)canGoNext;
- (BOOL)canAppendPathComponentToBaseURL:(id)arg1;
- (BOOL)needsInteraction;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;
- (void)viewDidLoad;
- (id)initWithContext:(id)arg1;

@end

