//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEAssistant.h>

#import "IDESourceControlCredentialViewDelegate-Protocol.h"

@class DVTReplacementView, NSImageView, NSPopUpButton, NSString, NSTextField, NSURL;

@interface IDESourceControlCredentialsAssistant : IDEAssistant <IDESourceControlCredentialViewDelegate>
{
    NSString *_alreadyTrustedFingerprint;
    NSURL *_oldURL;
    BOOL canGoForward;
    NSTextField *_addressField;
    NSPopUpButton *_typeButton;
    DVTReplacementView *_replacementView;
    NSImageView *_errorImage;
    NSTextField *_errorField;
}

@property __weak NSTextField *errorField; // @synthesize errorField=_errorField;
@property __weak NSImageView *errorImage; // @synthesize errorImage=_errorImage;
@property __weak DVTReplacementView *replacementView; // @synthesize replacementView=_replacementView;
@property __weak NSPopUpButton *typeButton; // @synthesize typeButton=_typeButton;
@property __weak NSTextField *addressField; // @synthesize addressField=_addressField;
@property BOOL canGoForward; // @synthesize canGoForward;
- (void)primitiveInvalidate;
- (id)nextAssistantIdentifier;
- (id)previousAssistantIdentifier;
- (BOOL)canGoBack;
- (BOOL)canCancel;
- (void)willGoNextOrFinish;
- (void)clearWarningAndProgressText;
- (void)showProgressText:(id)arg1;
- (void)showWarningText:(id)arg1;
- (void)viewDidLoad;
- (void)controlTextDidChange:(id)arg1;
- (id)credentialViewController;
- (id)downloadAssistantContext;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

