//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDESourceControlMultiChooserItem.h>

@class DVTSourceControlBranch, DVTSourceControlRemoteRepository, NSDictionary;

@interface IDESourceControlRepositoryChooserItem : IDESourceControlMultiChooserItem
{
    DVTSourceControlBranch *_currentBranch;
    DVTSourceControlBranch *_trackingBranch;
    DVTSourceControlRemoteRepository *_selectedRemote;
    DVTSourceControlBranch *_selectedBranch;
    NSDictionary *_remotes;
}

@property(retain) DVTSourceControlBranch *selectedBranch; // @synthesize selectedBranch=_selectedBranch;
@property(retain) DVTSourceControlRemoteRepository *selectedRemote; // @synthesize selectedRemote=_selectedRemote;
- (void)setSelectedItem:(id)arg1;
- (void)fetchRemotesWithCompletionBlock:(dispatch_block_t)arg1;
- (id)_defaultSelectionForItems:(id)arg1;
- (void)primitiveInvalidate;

@end

