//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDETemplateInstantiationAssistant.h>


@class NSArray, NSMutableDictionary, NSString, NSTextField, NSView;

@interface IDETemplateOptionsAssistant : IDETemplateInstantiationAssistant <NSComboBoxDataSource>
{
    NSView *_mainView;
    NSArray *_classNames;
    NSMutableDictionary *_controlsForOptionIds;
    BOOL _canGoForward;
    NSTextField *_firstTextField;
    NSArray *_sortedPrimaryOptions;
}

@property(readonly) NSArray *sortedPrimaryOptions; // @synthesize sortedPrimaryOptions=_sortedPrimaryOptions;
@property(retain) NSTextField *firstTextField; // @synthesize firstTextField=_firstTextField;
@property BOOL canGoForward; // @synthesize canGoForward=_canGoForward;
- (id)comboBox:(id)arg1 completedString:(id)arg2;
- (unsigned long long)comboBox:(id)arg1 indexOfItemWithStringValue:(id)arg2;
- (id)comboBox:(id)arg1 objectValueForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsInComboBox:(id)arg1;
- (id)classNamesForComboBox:(id)arg1;
- (void)writeStateToUserDefaults;
- (void)restoreSelectionFromUserDefaults;
- (void)setupOptionViews;
- (id)additionalOptions;
- (double)requiredViewSpacingForOption:(id)arg1;
- (id)createLabelForOption:(id)arg1;
- (id)createControlForOption:(id)arg1 withOptionArray:(id)arg2;
- (id)_valueProvidingOptionForOption:(id)arg1 fromOptionArray:(id)arg2;
- (void)_setControl:(id)arg1 forOptionIdentifier:(id)arg2;
- (id)controlForOptionIdentifier:(id)arg1;
- (void)_setAccessibilityForCell:(id)arg1 withOption:(id)arg2 prefix:(id)arg3;
- (id)assistantTitle;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;
- (void)primitiveInvalidate;
- (id)nextAssistantIdentifier;
- (void)updateOptions:(id)arg1;
- (void)setAssistantContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

