//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSDictionary, NSString, NSURL, NSView;

@protocol IDEVariablesViewQuickLookProvider <NSObject>
@property(readonly) NSView *quickLookView;
@property(readonly) int loadedState;
- (void)cancelLoading;
- (id)initWithDataValue:(id <IDEDataValue>)arg1 options:(NSDictionary *)arg2;

@optional
@property(readonly) NSString *extensionForTemporaryFile;
@property(readonly) NSURL *existingURLToOpen;
- (void)writeAtomicallyToTemporaryFile:(NSURL *)arg1;
@end

