//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDELocalizationWorkContext.h>

@class DVTFilePath, DVTLocale, IDEContainer<IDELocalizedContainer>, IDEGroup<IDELocalizedGroup>;

@interface _IDELocalizationAddFileReferenceContext : IDELocalizationWorkContext
{
    IDEContainer *_container;
    IDEGroup *_group;
    DVTLocale *_locale;
    DVTFilePath *_filePath;
}

@property(retain) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(retain) DVTLocale *locale; // @synthesize locale=_locale;
@property(retain) IDEGroup *group; // @synthesize group=_group;
@property(retain) IDEContainer *container; // @synthesize container=_container;
- (void)primitiveInvalidate;

@end

