//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSString;

@protocol IDEContainerItemCore <NSObject>
@property(readonly) id  parentContainer;
@property(copy) NSString *path;
@property(retain) id  parentGroup;
@end

