//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "IDEDistributionAppleProvidedContent-Protocol.h"

@class NSString;

@interface IDEDistributionAppleProvidedContentSwiftSupport : NSObject <IDEDistributionAppleProvidedContent>
{
}

@property(readonly) NSString *packagePath;
@property(readonly) NSString *archivePath;
@property(readonly) NSString *archiveOperationDestinationBuildSettingName;
- (BOOL)shouldCopySidecarContentFromArchive:(id)arg1;
- (BOOL)shouldRemoveForAppStoreDistributionDistributionItem:(id)arg1 shouldRemoveParentDirectory:(char *)arg2;
- (BOOL)isAppleProvidedContent:(id)arg1;
- (BOOL)shouldCodeSignDistributionItem:(id)arg1;
@property(readonly) NSString *mainAppStubCopySubpath;

@end

