//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDEDistributionProcessingPackagingStep.h>

@class NSString;

@interface IDEDistributionCreatePKGStep : IDEDistributionProcessingPackagingStep
{
    NSString *name;
}

+ (id)packagePathExtension;
+ (_Bool)supportsDryRun;
+ (BOOL)wantsPayloadDir;
@property(copy) NSString *name; // @synthesize name;
- (_Bool)runWithError:(id *)arg1;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;

@end

