//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDEContainerItemCore.h>

#import "IDEGroupCore-Protocol.h"

@class NSArray, NSString;

@interface IDEGroupCore : IDEContainerItemCore <IDEGroupCore>
{
    id  _parentContainer;
    NSString *_name;
    NSArray *_subitems;
}

@property(copy) NSArray *subitems; // @synthesize subitems=_subitems;
@property(copy) NSString *name; // @synthesize name=_name;
- (void)setParentContainer:(id)arg1;
@property(readonly) id  parentContainer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain) id  parentGroup;
@property(copy) NSString *path;
@property(readonly) Class superclass;

@end

