//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface IDEIPAProcessor : NSObject
{
}

+ (id)sharedInstance;
- (BOOL)compileBitcodeForPayloadAppAtPath:(id)arg1 toPath:(id)arg2 logAspect:(id)arg3 error:(id *)arg4;
- (BOOL)optimizePayloadAppAtPath:(id)arg1 toPath:(id)arg2 forDeviceFamily:(id)arg3 logAspect:(id)arg4 error:(id *)arg5;
- (id)consolidateDeviceFamiliesWithEquivalentTraits:(id)arg1;
- (id)applicableDeviceFamiliesForPayloadAtPath:(id)arg1 logAspect:(id)arg2 error:(id *)arg3;
- (BOOL)enumerateSupportedDeviceSetInfosForPayloadAppAtPath:(id)arg1 logAspect:(id)arg2 error:(id *)arg3 usingBlock:(dispatch_block_t)arg4;
- (id)runIPAToolWithInputPath:(id)arg1 outputPath:(id)arg2 arguments:(id)arg3 logAspect:(id)arg4 outError:(id *)arg5;
- (id)binSearchPathForIPATool;

@end

