//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDELocalizationWorkContext.h>

@class IDELocalizedResourceAdaptor;

@interface IDELocalizedResourceAdaptorWorkContext : IDELocalizationWorkContext
{
    IDELocalizedResourceAdaptor *_adaptor;
}

+ (id)contextWithParent:(id)arg1 adaptor:(id)arg2;
+ (id)contextWithParent:(id)arg1 dryRun:(BOOL)arg2 adaptor:(id)arg3;
@property(retain) IDELocalizedResourceAdaptor *adaptor; // @synthesize adaptor=_adaptor;
- (void)primitiveInvalidate;

@end

