//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSString;

@interface IDELocalizationRecordItem : NSObject
{
    NSString *_message;
    NSString *_className;
    IDELocalizationRecordItem *_subItem;
}

+ (id)itemWithMessage:(id)arg1 className:(id)arg2 subItem:(id)arg3;
@property(retain) IDELocalizationRecordItem *subItem; // @synthesize subItem=_subItem;
@property(retain) NSString *className; // @synthesize className=_className;
@property(retain) NSString *message; // @synthesize message=_message;
- (BOOL)containsString:(id)arg1;
- (id)description;

@end

