//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTRegularExpression, NSObject<OS_dispatch_queue>;

@interface IDEOCUnitTestOutputParser : NSObject
{
    id  _delegate;
    DVTRegularExpression *_testSuiteStartedRegex;
    DVTRegularExpression *_testSuiteFinishedRegex;
    DVTRegularExpression *_testSuiteExecutedRegex;
    DVTRegularExpression *_testCaseStartedRegex;
    DVTRegularExpression *_testCaseMeasuredPerformanceMetricRegex;
    DVTRegularExpression *_testCaseFinishedRegex;
    DVTRegularExpression *_testCaseFailedRegex;
    NSObject *_processingQueue;
    NSObject *_delegateQueue;
    BOOL _outputsToConsole;
}

+ (void)_initializeRegularExpressionsIfNeeded;
@property BOOL outputsToConsole; // @synthesize outputsToConsole=_outputsToConsole;
@property __weak id  delegate; // @synthesize delegate=_delegate;
- (void)performDelegateBlock:(dispatch_block_t)arg1;
- (void)performParserBlock:(dispatch_block_t)arg1;
- (void)processConsoleText:(id)arg1;
- (id)filterTestSuiteIdentifierFromString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

