//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTInvalidation-Protocol.h"

@class DVTNotificationToken, DVTStackBacktrace, NSString;

@interface IDEProvisioningProfileSource : NSObject <DVTInvalidation>
{
    DVTNotificationToken *_addedProfilesNoteToken;
    DVTNotificationToken *_removedProfilesNoteToken;
    id  _delegate;
}

+ (void)initialize;
@property(retain, nonatomic) id  delegate; // @synthesize delegate=_delegate;
- (id)provisioningProfiles;
- (id)_profileManager;
- (void)primitiveInvalidate;
- (id)init;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

