//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTInvalidation-Protocol.h"

@class DVTStackBacktrace, IDETestRunner, NSMutableArray, NSMutableSet, NSString;

@interface IDETestOperationsObserver : NSObject <DVTInvalidation>
{
    NSMutableSet *_testRunners;
    NSMutableSet *_unitTestsObservers;
    NSMutableArray *_errors;
    BOOL _hasFinished;
    dispatch_block_t _finishBlock;
    IDETestRunner *_currentTestRunner;
}

+ (void)initialize;
@property(retain) IDETestRunner *currentTestRunner; // @synthesize currentTestRunner=_currentTestRunner;
@property BOOL hasFinished; // @synthesize hasFinished=_hasFinished;
@property(copy) dispatch_block_t finishBlock; // @synthesize finishBlock=_finishBlock;
- (void)testRunner:(id)arg1 didFinishTest:(id)arg2 withTestResult:(id)arg3 rawOutput:(id)arg4;
- (void)testRunner:(id)arg1 didFailTest:(id)arg2 withTestResultMessage:(id)arg3 rawOutput:(id)arg4;
- (void)testRunner:(id)arg1 test:(id)arg2 didMeasurePerformanceMetric:(id)arg3 rawOutput:(id)arg4;
- (void)testRunner:(id)arg1 didOutput:(id)arg2;
- (void)testRunner:(id)arg1 test:(id)arg2 didFinishActivity:(id)arg3;
- (void)testRunner:(id)arg1 test:(id)arg2 willStartActivity:(id)arg3;
- (void)testRunner:(id)arg1 didStartTest:(id)arg2 withRawOutput:(id)arg3;
- (void)testSuiteDidFinish:(long long)arg1 withFailures:(long long)arg2 unexpected:(long long)arg3 testDuration:(double)arg4 totalDuration:(double)arg5 rawOutput:(id)arg6;
- (void)testSuite:(id)arg1 willFinishAt:(id)arg2 rawOutput:(id)arg3;
- (void)testSuite:(id)arg1 didStartAt:(id)arg2 rawOutput:(id)arg3;
- (void)testRunner:(id)arg1 willFinishWithError:(id)arg2 didCancel:(BOOL)arg3;
- (void)_considerFinishing;
- (void)testRunner:(id)arg1 didLaunchTestSessionForScheme:(id)arg2 withDisplayName:(id)arg3;
- (void)testRunnerDidStartRunningTests:(id)arg1;
- (void)addUnitTestsObserver:(id)arg1;
- (void)addTestRunner:(id)arg1;
- (void)primitiveInvalidate;
- (id)init;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

