//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTLocking-Protocol.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface DVTDispatchLock : NSObject <DVTLocking>
{
    NSObject *_queue;
}

+ (id)readWriteDispatchLockWithDebugName:(id)arg1;
+ (id)recursiveDispatchLockWithDebugName:(id)arg1;
+ (id)dispatchLockWithDebugName:(id)arg1;
@property(readonly) NSObject *queue; // @synthesize queue=_queue;
- (void)performLockedBlockAsyncUnlessRecursing:(dispatch_block_t)arg1;
- (void)setQualityOfService:(long long)arg1;
- (void)afterTimeInterval:(double)arg1 asyncPerformLockedBlock:(dispatch_block_t)arg2;
- (void)asyncPerformLockedWriterBlock:(dispatch_block_t)arg1;
- (void)asyncPerformLockedReaderBlock:(dispatch_block_t)arg1;
- (void)performLockedWriterBlock:(dispatch_block_t)arg1;
- (void)performLockedReaderBlock:(dispatch_block_t)arg1;
- (void)asyncPerformLockedBlock:(dispatch_block_t)arg1;
- (void)performLockedBlock:(dispatch_block_t)arg1;
@property(readonly) NSString *debugName;
- (void)dealloc;
- (id)initWithDebugName:(id)arg1;
- (id)initWithDebugName:(id)arg1 isRecursive:(BOOL)arg2;
- (void)dvt_asyncPerformLockedBlock:(dispatch_block_t)arg1;
- (void)dvt_performLockedBlock:(dispatch_block_t)arg1;

@end

