//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTCancellable-Protocol.h"
#import "DVTPromise-Protocol.h"

@class DVTDispatchLock, DVTStackBacktrace, NSError, NSObject<OS_dispatch_group>, NSString;

@interface DVTFuture : NSObject <DVTPromise, DVTCancellable>
{
    DVTDispatchLock *_lock;
    NSObject *_cond_group;
    long long _state;
    _Bool _hasTimeout;
    _Bool _timedOut;
    long long _progress;
    NSError *_error;
    id _result;
    DVTStackBacktrace *_initBacktrace;
    DVTStackBacktrace *_finishBacktrace;
    struct vector _progressBlocks;
    struct vector _finishBlocks;
    struct unordered_map _linkedSubFutures;
}

+ (id)futureWithOperation:(id)arg1;
+ (id)cancelledFuture;
+ (id)futureWithResult:(id)arg1;
+ (id)futureWithError:(id)arg1;
+ (id)futureWithBlock:(dispatch_block_t)arg1;
+ (id)runOperation:(id)arg1;
+ (id)trackOperation:(id)arg1;
- (id).cxx_construct;
- (void)trackFuture:(id)arg1;
- (void)trackFuture:(id)arg1 progress:(float)arg2 cancel:(BOOL)arg3 result:(BOOL)arg4 error:(BOOL)arg5;
- (void)updateProgressFromReporters;
- (void)failWithError:(id)arg1 afterTimeout:(double)arg2;
- (void)succeedWithResult:(id)arg1 afterTimeout:(double)arg2;
- (void)cancelAfterTimeout:(double)arg1;
- (void)_setState:(long long)arg1 result:(id)arg2 error:(id)arg3 afterTimeout:(double)arg4;
- (void)succeedWithResult:(id)arg1;
- (void)failWithError:(id)arg1;
- (void)cancel;
- (void)setState:(long long)arg1 result:(id)arg2 error:(id)arg3;
- (dispatch_block_t)_internalSetState:(long long)arg1 result:(id)arg2 error:(id)arg3;
- (id)future;
- (void)setProgress:(long long)arg1;
@property(readonly, copy) NSString *description;
- (id)_description;
- (void)observeFinishWithDispatchGroup:(id)arg1;
- (void)observeSuccess:(dispatch_block_t)arg1;
- (void)observeFailure:(dispatch_block_t)arg1;
- (void)observeCancellation:(dispatch_block_t)arg1;
- (void)observeFinishOnQueue:(id)arg1 withBlock:(dispatch_block_t)arg2;
- (void)observeFinish:(dispatch_block_t)arg1;
- (void)observeProgress:(dispatch_block_t)arg1;
@property(readonly, getter=isCancelled) BOOL cancelled;
- (long long)waitUntilFinished;
- (id)result;
- (id)error;
- (void)_signalFinished;
- (void)_waitUntilFinished;
- (void)dealloc;
- (id)initWithResult:(id)arg1;
- (id)initWithError:(id)arg1;
- (id)initWithBlock:(dispatch_block_t)arg1;
- (id)init;
- (id)then:(dispatch_block_t)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

