//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSArray;

@interface _IDETestReportAssertionsOutlineObject : NSObject
{
    id  _test;
    id  _testRun;
    NSArray *_failureSummaries;
}

@property(copy) NSArray *failureSummaries; // @synthesize failureSummaries=_failureSummaries;
@property(retain) id  testRun; // @synthesize testRun=_testRun;
@property(retain) id  test; // @synthesize test=_test;

@end

