//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSArrayController, NSPopUpButton;

@interface _IDEDistributionMethodTableCellView : NSTableCellView
{
    NSPopUpButton *_popUpButton;
    NSArrayController *_methodsArrayController;
}

@property(retain) NSArrayController *methodsArrayController; // @synthesize methodsArrayController=_methodsArrayController;
@property(retain) NSPopUpButton *popUpButton; // @synthesize popUpButton=_popUpButton;

@end

