//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTTableRowView;

@protocol DVTTableRowViewMouseInsideDelegate <NSObject>
- (void)tableRowView:(DVTTableRowView *)arg1 mouseInside:(BOOL)arg2;
@end

