//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSImage, NSString, NSURL;

@interface IDEAppChooserModelObject : NSObject
{
    BOOL _isRecent;
    BOOL _isGroupHeader;
    NSString *_displayName;
    NSImage *_image;
    NSURL *_url;
    id  _application;
}

@property BOOL isGroupHeader; // @synthesize isGroupHeader=_isGroupHeader;
@property BOOL isRecent; // @synthesize isRecent=_isRecent;
@property(retain) id  application; // @synthesize application=_application;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain) NSImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)debugDescription;
- (id)keyPathsForValuesAffectingDisplayName;
- (id)keyPathsForValuesAffectingUrl;

@end

