//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSButton;

@interface IDEBatchFindResultCheckBoxTableCellView : NSTableCellView
{
    NSButton *_checkBox;
}

@property(retain) NSButton *checkBox; // @synthesize checkBox=_checkBox;

@end

