//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "IDEKeyDrivenNavigableItemRepresentedObject-Protocol.h"

@class DVTDocumentLocation, DVTFileDataType, DVTFilePath, IDEBatchFindCandidateFile, IDEFileReference, IDEIndex, NSArray, NSImage, NSMutableArray, NSString;

@interface IDEBatchFindResultGroup : NSObject <IDEKeyDrivenNavigableItemRepresentedObject, NSCopying>
{
    NSArray *_results;
    NSMutableArray *_filteredResults;
    unsigned long long _replaceableCount;
    unsigned long long _filteredReplaceableCount;
    id _representingNavItem;
    BOOL _isPropogatingReplacementInclusionToChildren;
    BOOL _symbolLookUpEnabled;
    int _shouldIncludeInReplacement;
    IDEBatchFindCandidateFile *_fileCandidate;
    DVTFilePath *_filePath;
    IDEIndex *_index;
    NSString *_groupTitle;
    id  _delegate;
}

+ (id)keyPathsForValuesAffectingDisplayImage;
@property(retain) id  delegate; // @synthesize delegate=_delegate;
@property(copy) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(nonatomic) int shouldIncludeInReplacement; // @synthesize shouldIncludeInReplacement=_shouldIncludeInReplacement;
@property(getter=isSymbolLookUpEnabled) BOOL symbolLookUpEnabled; // @synthesize symbolLookUpEnabled=_symbolLookUpEnabled;
@property __weak IDEIndex *index; // @synthesize index=_index;
@property(readonly) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(readonly) IDEBatchFindCandidateFile *fileCandidate; // @synthesize fileCandidate=_fileCandidate;
- (void)stopObservingFilePath;
- (void)startObservingFilePath;
@property(readonly) BOOL doesBackingFileExist;
- (void)childReplacementInclusionStateChanged:(id)arg1;
- (void)_beginSymbolLookupForResults;
- (void)resetHiddenResults;
- (void)hideResultsWithIndexes:(id)arg1;
@property(readonly) NSString *displaySubtitle;
@property(readonly) NSImage *displayImage;
@property(readonly) NSString *displayTitle;
@property(readonly) unsigned long long replaceableCount;
@property(readonly) NSArray *results;
- (void)setResults:(id)arg1;
- (void)setDelegate:(id)arg1 navigableItem:(id)arg2;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithResults:(id)arg1 fromFilePath:(id)arg2;
- (id)initWithResults:(id)arg1 fromFileCandidate:(id)arg2;
- (BOOL)isEditable;
- (id)ideModelObjectTypeIdentifier;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

