//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface IDECoverageReportMeterBar : NSView
{
    BOOL _useAlternateColor;
    double _doubleValue;
}

@property(nonatomic) BOOL useAlternateColor; // @synthesize useAlternateColor=_useAlternateColor;
@property(nonatomic) double doubleValue; // @synthesize doubleValue=_doubleValue;
- (void)drawRect:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)updateWithBarValue:(double)arg1 useAlternateColor:(BOOL)arg2;

@end

