//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEEditorDocument.h>

@class DVTObservingToken, IDEDebugSession, IDELaunchSession;

@interface IDEDebugGaugeReportDocument : IDEEditorDocument
{
    IDELaunchSession *_launchSession;
    DVTObservingToken *_launchSessionObservingToken;
    IDEDebugSession *_debugSession;
}

+ (BOOL)shouldUnlockFileURLBeforeMakingChanges;
- (id)launchSession;
- (int)readOnlyStatus;
- (void)editorDocumentWillClose;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

