//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDENavigableItemDomainProvider.h>

#import "IDEKeyDrivenNavigableItemRepresentedObject-Protocol.h"

@class DVTDocumentLocation, DVTFileDataType, DVTObservingToken, IDEFileReference, IDEWorkspace, NSImage, NSString;

@interface IDEDebugGaugeDomainProvider : IDENavigableItemDomainProvider <IDEKeyDrivenNavigableItemRepresentedObject>
{
    IDEWorkspace *_workspace;
    DVTObservingToken *_workspaceStateObservingToken;
}

+ (id)domainObjectForWorkspace:(id)arg1;
+ (id)keyPathsForValuesAffectingGaugeNavigables;
+ (id)providerForWorkspace:(id)arg1;
+ (id)launchSessionFromURL:(id)arg1;
+ (id)URLForScheme:(id)arg1 launchSession:(id)arg2;
+ (id)URLForScheme:(id)arg1 launchSession:(id)arg2 otherQueryString:(id)arg3;
+ (void)initialize;
@property(retain) IDEWorkspace *workspace; // @synthesize workspace=_workspace;
@property(readonly) NSString *navigableItem_name;
- (unsigned long long)navigableItem_indexOfRepresentedObjectForIdentifier:(id)arg1 inRelationshipKeyPath:(id)arg2;
- (id)navigableItem_identifierForRepresentedObjectAtIndex:(unsigned long long)arg1 inRelationshipKeyPath:(id)arg2;
- (id)gaugeNavigables;
- (id)initWithWorkspace:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

