//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSArray;

@interface IDEGraphModel : NSObject
{
    id  _delegate;
    id  _chartsModificationDelegate;
    NSArray *_charts;
}

@property(retain) NSArray *charts; // @synthesize charts=_charts;
@property __weak id  chartsModificationDelegate; // @synthesize chartsModificationDelegate=_chartsModificationDelegate;
@property __weak id  delegate; // @synthesize delegate=_delegate;
- (id)_chartNamed:(id)arg1;
- (id)chartNamed:(id)arg1;
- (id)init;

@end

