//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDENavigableItemFilteringCoordinator.h>

@class DVTTimeSlicedMainThreadWorkQueue, NSMutableDictionary;

@interface IDENavigableItemAsyncFilteringCoordinator : IDENavigableItemFilteringCoordinator
{
    NSMutableDictionary *_filteringProxiesByKey;
    DVTTimeSlicedMainThreadWorkQueue *_itemsToFilterQueue;
    DVTTimeSlicedMainThreadWorkQueue *_itemsToInvalidateChildArrangedItemsQueue;
    long long _currentFilteringGeneration;
}

+ (id)keyPathsForValuesAffectingPerformingFiltering;
@property long long currentFilteringGeneration; // @synthesize currentFilteringGeneration=_currentFilteringGeneration;
@property(readonly) DVTTimeSlicedMainThreadWorkQueue *itemsToInvalidateChildArrangedItemsQueue; // @synthesize itemsToInvalidateChildArrangedItemsQueue=_itemsToInvalidateChildArrangedItemsQueue;
@property(readonly) DVTTimeSlicedMainThreadWorkQueue *itemsToFilterQueue; // @synthesize itemsToFilterQueue=_itemsToFilterQueue;
- (void)_handleObjectGraphDidChange:(id)arg1;
- (void)_handleItemsPropertiesDidChange:(id)arg1;
- (void)_markItem:(id)arg1 matches:(BOOL)arg2;
- (void)_invalidateArrangedChildrenOfFilterProxies;
- (void)_itemInvalidateMatchState:(id)arg1;
- (BOOL)_itemGenerationIsCurrent:(id)arg1;
- (BOOL)_itemMatches:(id)arg1;
- (id)_arrangeItems:(id)arg1 ofItem:(id)arg2;
- (void)_performFilterEvaluationOf:(id)arg1;
- (void)_beginFilteringFrom:(id)arg1;
- (BOOL)performingFiltering;
- (void)_filterDidChange;
- (void)_stopAllWork;
- (void)resumeFiltering;
- (void)suspendFiltering;
- (void)primitiveInvalidate;
- (id)init;
- (id)_filteredItemProxyForKey:(id)arg1;
- (void)_setFilteredItemProxy:(id)arg1 forKey:(id)arg2;
- (id)_filteredItemProxyForItems:(id)arg1;
- (id)_filteringProxiesByKey;

@end

