//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEOnboardingPage.h>

@class NSTextView, NSView;

@interface IDEOnboardingTutorialRunViewController : IDEOnboardingPage
{
    NSTextView *_textView;
    NSView *_translucentView;
}

@property __weak NSView *translucentView; // @synthesize translucentView=_translucentView;
@property NSTextView *textView; // @synthesize textView=_textView;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)_addDocAndAPILinkToText:(id)arg1;
- (void)viewDidLoad;

@end

