//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEOpenQuicklyIndexMatchProvider.h>

@class NSDictionary;

@interface IDEOpenQuicklyProjectMatchProvider : IDEOpenQuicklyIndexMatchProvider
{
    NSDictionary *_containerQueryMatches;
}

+ (id)sharedIndexQueryQueue;
- (id)matchesFromCollectedData:(id)arg1;
- (id)collectDataForInput:(id)arg1 index:(id)arg2 currentGeneration:(unsigned int *)arg3 localGeneration:(unsigned int)arg4;
- (void)restartQuery;
- (id)containerQueryMatches;
- (id)initWithSearchContext:(id)arg1;

@end

