//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface IDEPlaygroundCreationHelper : NSObject
{
}

+ (void)createNewPlaygroundPageIn:(id)arg1 near:(id)arg2 inWorkspaceTabController:(id)arg3 completionBlock:(dispatch_block_t)arg4;
+ (void)_createNewPlaygroundPageInPlayground:(id)arg1 near:(id)arg2 inWorkspaceTabController:(id)arg3 completionBlock:(dispatch_block_t)arg4;
+ (unsigned long long)_indexToInsertNewPageInPlayground:(id)arg1 near:(id)arg2;
+ (void)_performHoldingLock:(id)arg1 errors:(id)arg2 operation:(dispatch_block_t)arg3;
+ (void)createNewPlaygroundFromTemplateInWorkspaceWindowController:(id)arg1 platformIdentifier:(id)arg2 withContextSetupBlock:(dispatch_block_t)arg3;
+ (id)_createUntitledWorkspace;

@end

