//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTInvalidation-Protocol.h"

@class DVTDelayedInvocation, DVTStackBacktrace, NSArray, NSString, Xcode3TargetBuildSettingsCoordinator, Xcode3TargetEntitlementsCoordinator, Xcode3TargetInfoPlistCoordinator, Xcode3TargetLinkedFrameworksCoordinator, Xcode3TargetPortalEntitlementsCoordinator<IDEAppIDFeatureDelegate>;

@interface IDEProjectItemModel : NSObject <DVTInvalidation>
{
    NSArray *_flightChecks;
    id  _targetCapabilitiesContext;
    id  _item;
    DVTDelayedInvocation *_delayedUpdateInvocation;
}

+ (void)initialize;
@property(readonly) DVTDelayedInvocation *delayedUpdateInvocation; // @synthesize delayedUpdateInvocation=_delayedUpdateInvocation;
@property(readonly) id  item; // @synthesize item=_item;
@property(readonly) id  targetCapabilitiesContext; // @synthesize targetCapabilitiesContext=_targetCapabilitiesContext;
@property(readonly, nonatomic) NSArray *flightChecks; // @synthesize flightChecks=_flightChecks;
@property(readonly) Xcode3TargetInfoPlistCoordinator *infoPlistCoordinator;
@property(readonly) Xcode3TargetLinkedFrameworksCoordinator *linkedFrameworksCoordinator;
@property(readonly) Xcode3TargetPortalEntitlementsCoordinator *portalEntitlementsCoordinator;
@property(readonly) Xcode3TargetEntitlementsCoordinator *entitlementsCoordinator;
@property(readonly) Xcode3TargetBuildSettingsCoordinator *buildSettingsCoordinator;
- (void)runFlightChecks;
@property(readonly) BOOL requiresAccountAndTeamSelection;
@property(readonly) BOOL isEnabledUsingEducatedGuess;
- (void)setEnabled:(BOOL)arg1 flightCheckContext:(id)arg2;
@property(readonly, getter=isEnabled) BOOL enabled;
- (void)publishStateWithContext:(id)arg1;
- (void)modelWasDisabled;
- (void)modelWasEnabledWithContext:(id)arg1;
- (void)updateWithContext:(id)arg1;
- (void)targetCoordinatorChanged:(id)arg1;
- (void)primitiveInvalidate;
- (id)init;
- (id)initWithCapabilitiesContext:(id)arg1 item:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

