//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEViewController.h>

@class DVTDelayedInvocation, DVTTableView, NSArray, NSMutableSet, NSTableColumn;

@interface IDEProvisioningSigningIdentitiesViewController : IDEViewController
{
    NSMutableSet *_busySigningIdentities;
    DVTDelayedInvocation *_tableViewUpdateBlock;
    id  _delegate;
    NSArray *_signingIdentities;
    NSTableColumn *_nameColumn;
    NSTableColumn *_actionColumn;
    DVTTableView *_tableView;
}

@property(retain, nonatomic) DVTTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSTableColumn *actionColumn; // @synthesize actionColumn=_actionColumn;
@property(retain, nonatomic) NSTableColumn *nameColumn; // @synthesize nameColumn=_nameColumn;
@property(copy, nonatomic) NSArray *signingIdentities; // @synthesize signingIdentities=_signingIdentities;
@property(retain, nonatomic) id  delegate; // @synthesize delegate=_delegate;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)_selectedIdentityForContextMenu;
- (BOOL)validateMenuItem:(id)arg1;
- (void)exportIdentity:(id)arg1;
- (void)resetSigningIdentity:(id)arg1;
- (void)createSigningIdentity:(id)arg1;
- (id)_logAspect;
- (void)didEndProcessingSigningIdentity:(id)arg1;
- (void)didBeginProcessingSigningIdentity:(id)arg1;
- (void)_tableViewNeedsUpdate;
- (void)primitiveInvalidate;
- (void)awakeFromNib;

@end

