//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import "IDETextSubstitutionTemplateInstantiationContext-Protocol.h"

@class IDEWorkspace;

@interface IDERefactoringCreateSuperclassTemplateInstantiationContext : IDETextSubstitutionTemplateInstantiationContext
{
    IDEWorkspace *_workspace;
}

@property(retain, nonatomic) IDEWorkspace *workspace; // @synthesize workspace=_workspace;

@end

