//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEAssistant.h>

#import "IDEComparisonEditorDataSource-Protocol.h"
#import "IDEReviewFilesDataSource-Protocol.h"

@class DVTBorderedView, DVTObservingToken, IDENavigableItemAsyncFilteringCoordinator, IDENavigatorDataCell, IDEReviewFilesViewController, NSArray, NSMapTable, NSMutableSet, NSObject<OS_dispatch_semaphore>, NSOperationQueue, NSString;

@interface IDESwiftMigrationReviewChangesAssistant : IDEAssistant <IDEReviewFilesDataSource, IDEComparisonEditorDataSource>
{
    NSMapTable *_editorDocumentByFilePath;
    IDENavigableItemAsyncFilteringCoordinator *_navItemCoordinator;
    IDENavigatorDataCell *_containerFileReferenceDataCell;
    IDENavigatorDataCell *_groupDataCell;
    IDENavigatorDataCell *_fileReferenceDataCell;
    IDEReviewFilesViewController *_reviewFilesViewController;
    DVTBorderedView *_borderedView;
    DVTObservingToken *_comparisonEditorObservingToken;
    dispatch_block_t _completionBlock;
    NSOperationQueue *_operationQueue;
    NSMutableSet *_readOnlyStatusObservationTokens;
    unsigned long long _numCheckedFilePaths;
    NSObject *_completionSemaphore;
    NSMutableSet *_bindingTokens;
    NSArray *_workspaceNavigableItems;
    NSArray *_flatNavigableItems;
    NSArray *_originalFilePaths;
}

+ (id)keyPathsForValuesAffectingCanFinish;
@property(copy) NSArray *originalFilePaths; // @synthesize originalFilePaths=_originalFilePaths;
@property(copy) NSArray *flatNavigableItems; // @synthesize flatNavigableItems=_flatNavigableItems;
@property(copy) NSArray *workspaceNavigableItems; // @synthesize workspaceNavigableItems=_workspaceNavigableItems;
- (BOOL)shouldSelectFirstDiff;
- (id)navigableItemsForSecondaryDocumentLocation:(id)arg1 usingNavigableItemCoordinator:(id)arg2 completionBlock:(dispatch_block_t)arg3;
- (id)navigableItemsForPrimaryDocumentLocation:(id)arg1 usingNavigableItemCoordinator:(id)arg2 completionBlock:(dispatch_block_t)arg3;
- (id)documentForSecondaryDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (id)documentForPrimaryDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (id)_documentForLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (BOOL)reviewFilesNavigator:(id)arg1 outlineView:(id)arg2 showCheckboxForNavigableItem:(id)arg3;
- (id)reviewFilesNavigator:(id)arg1 documentLocationForNavigableItem:(id)arg2;
- (id)reviewFilesNavigator:(id)arg1 outlineView:(id)arg2 dataCellForNavigableItem:(id)arg3;
- (id)_fileReferenceCell;
- (id)_groupCell;
- (id)_containerFileReferenceCell;
@property(readonly, copy) NSArray *issueNavigableItems;
- (id)fileSystemNavigableItems;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (BOOL)navItemRepresentsOriginalFile:(id)arg1;
- (void)loadView;
- (id)_snapshotContainerItem:(id)arg1 customizationBlock:(dispatch_block_t)arg2;
- (void)_setInitialSelectionForNavigatorOutlineView:(id)arg1;
- (BOOL)_selectedTargetsContainFilePath:(id)arg1;
- (void)finishWithCompletionBlock:(dispatch_block_t)arg1;
- (void)_convertedEditorDocument:(id)arg1 didSave:(BOOL)arg2 contextInfo:(void *)arg3;
- (void)_applyChanges;
- (void)_updateBuildSettingsAndFinish;
- (void)_finishWithError:(id)arg1;
- (id)_checkedDocuments;
- (BOOL)canFinish;
- (BOOL)canGoBack;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

