//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSString;

@protocol IDESourceControlCredentialViewDelegate <NSObject>
- (void)clearWarningAndProgressText;
- (void)showProgressText:(NSString *)arg1;
- (void)showWarningText:(NSString *)arg1;

@optional
- (void)viewNeedsHeight:(double)arg1;
@end

