//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTInvalidation-Protocol.h"
#import "DVTReplacementViewDelegate-Protocol.h"

@class DVTBorderedView, DVTObservingToken, DVTReplacementView, DVTSearchField, DVTSourceControlWorkspace, DVTSplitView, DVTStackBacktrace, IDESourceControlWorkspaceConfigNavigator, IDEWorkspace, NSArray, NSButton, NSString, NSTabView, NSTextField, NSView;

@interface IDESourceControlWorkspaceHistoryWindowController : NSWindowController <DVTInvalidation, DVTReplacementViewDelegate, NSWindowDelegate>
{
    unsigned long long _searchType;
    NSTextField *_titleField;
    DVTReplacementView *_logReplacementView;
    NSView *_sourceListView;
    IDESourceControlWorkspaceConfigNavigator *_navigator;
    NSTabView *_tabView;
    DVTBorderedView *_detailBorderedView;
    NSButton *_doneButton;
    DVTSearchField *_searchField;
    DVTSplitView *_splitView;
    BOOL _hidesSourceList;
    id _didScanToken;
    DVTObservingToken *_outlineViewSelectionToken;
    NSArray *previousSelectedObjects;
    BOOL _isScanningForWorkingCopies;
    IDEWorkspace *_workspace;
    DVTSourceControlWorkspace *_scmWorkspace;
    NSString *_startingSearchRevision;
    NSString *_endingSearchRevision;
}

+ (void)initialize;
@property(copy) NSString *endingSearchRevision; // @synthesize endingSearchRevision=_endingSearchRevision;
@property(copy) NSString *startingSearchRevision; // @synthesize startingSearchRevision=_startingSearchRevision;
@property(retain) DVTSourceControlWorkspace *scmWorkspace; // @synthesize scmWorkspace=_scmWorkspace;
@property BOOL isScanningForWorkingCopies; // @synthesize isScanningForWorkingCopies=_isScanningForWorkingCopies;
@property(retain) IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)primitiveInvalidate;
- (void)_updateSearchForRevision;
- (void)updateSearchMenuState;
@property unsigned long long searchType;
- (void)updateSearchPlaceholderString;
- (void)beginSearch:(id)arg1;
- (id)logViewController;
- (void)done:(id)arg1;
- (void)beginSheetForWindow:(id)arg1;
- (void)_waitForWorkspaceScan;
- (BOOL)splitView:(id)arg1 shouldHideDividerAtIndex:(long long)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (void)_loadWorkingCopies;
- (void)selectSearchType:(id)arg1;
- (void)loadWindow;
- (id)_logViewController;
- (id)windowNibName;
- (id)initWithWindow:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

