//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSTextView;

@interface IDETestReportAssertionPopoverViewController : NSViewController
{
    NSTextView *_textView;
}

@property NSTextView *textView; // @synthesize textView=_textView;
- (void)setAssertionText:(id)arg1;
- (void)viewDidLoad;

@end

