//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEViewController.h>

@class NSPopUpButton, NSString;

@interface IDEUITestingTargetSelectorViewController : IDEViewController
{
    BOOL _shouldSetBundleLoader;
    id  _unitTestBlueprint;
    NSString *_blueprintIdentifierToTest;
    NSPopUpButton *_testHostPopUp;
}

@property(retain) NSPopUpButton *testHostPopUp; // @synthesize testHostPopUp=_testHostPopUp;
@property(nonatomic) BOOL shouldSetBundleLoader; // @synthesize shouldSetBundleLoader=_shouldSetBundleLoader;
@property(retain, nonatomic) NSString *blueprintIdentifierToTest; // @synthesize blueprintIdentifierToTest=_blueprintIdentifierToTest;
@property(retain, nonatomic) id  unitTestBlueprint; // @synthesize unitTestBlueprint=_unitTestBlueprint;
- (void)_rebuildTestHostPopUp;
- (id)filteredBlueprints;
- (id)selectedBlueprint;
- (id)blueprintForMenuItem:(id)arg1;
- (void)selectBlueprint:(id)arg1;
- (void)updateUI;
- (void)updateUnitTestBlueprint;
- (void)loadView;
- (void)primitiveInvalidate;
- (id)initWithUnitTestBlueprint:(id)arg1;

@end

