//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface _IDECoverageProcessedRange : NSObject
{
    BOOL _isFirstSubrangeInLine;
    BOOL _isLastSubrangeInLine;
    unsigned long long _lineNumber;
    unsigned long long _startingCol;
    struct _NSRange _processedRange;
}

@property BOOL isLastSubrangeInLine; // @synthesize isLastSubrangeInLine=_isLastSubrangeInLine;
@property BOOL isFirstSubrangeInLine; // @synthesize isFirstSubrangeInLine=_isFirstSubrangeInLine;
@property unsigned long long startingCol; // @synthesize startingCol=_startingCol;
@property unsigned long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property struct _NSRange processedRange; // @synthesize processedRange=_processedRange;

@end

