//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class _IDETestReportTestRunPickerRow;

@interface _IDETestReportTestRunPickerMenuItemPayload : NSObject
{
    _IDETestReportTestRunPickerRow *_pickerRow;
    id  _testRun;
}

@property(retain) id  testRun; // @synthesize testRun=_testRun;
@property(retain) _IDETestReportTestRunPickerRow *pickerRow; // @synthesize pickerRow=_pickerRow;

@end

