//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class IDETestReportViewController, NSButton;

@interface _IDETestReportsPerfMetricTableCellView : NSTableCellView
{
    NSButton *_button;
    id  _testRun;
    id  _test;
    IDETestReportViewController *_reportViewController;
}

@property __weak IDETestReportViewController *reportViewController; // @synthesize reportViewController=_reportViewController;
@property(retain) id  test; // @synthesize test=_test;
@property(retain) id  testRun; // @synthesize testRun=_testRun;
@property(retain) NSButton *button; // @synthesize button=_button;
- (void)showPerfPopover:(id)arg1;

@end

