//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTSourceControlRepository, NSError;

@protocol DVTSourceControlAuthenticationFailureHandler <NSObject>
- (void)handleAuthenticationFailure:(NSError *)arg1 forRepository:(DVTSourceControlRepository *)arg2 context:(id)arg3 completionBlock:(void (^)(BOOL))arg4;
@end

