//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTAppIDFeatures, NSDictionary, NSString;

@interface IDECodesignIssueResolverAppIDRequirements : NSObject
{
    NSString *_bundleIdentifier;
    NSDictionary *_requiredEntitlements;
    DVTAppIDFeatures *_requiredFeatures;
}

+ (id)appIDRequirementsWithBundleIdentifier:(id)arg1 entitlements:(id)arg2 features:(id)arg3;
@property(retain) DVTAppIDFeatures *requiredFeatures; // @synthesize requiredFeatures=_requiredFeatures;
@property(retain) NSDictionary *requiredEntitlements; // @synthesize requiredEntitlements=_requiredEntitlements;
@property(retain) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@end

