//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import "IDEContainer-Protocol.h"

@interface IDEContainer (IDENewFileTemplateAdditions)
- (id)ide_defaultNewFileTemplate;
- (id)ide_defaultNewFileTemplateForPath:(id)arg1;
- (id)ide_templateForName:(id)arg1 andCategory:(id)arg2;
@end

