//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSString, NSWindow;

@protocol IDEContinuousIntegrationNewServiceAccountController <NSObject>
- (void)beginSheetModalForWindow:(NSWindow *)arg1 connectionAddress:(NSString *)arg2 completionBlock:(void (^)(long long, id, NSError *))arg3;
@end

