//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEDistributionStepViewController.h>

@class NSLayoutConstraint;

@interface IDEDistributionManifestStepViewController : IDEDistributionStepViewController
{
    NSLayoutConstraint *_centeredViewHeightConstraint;
}

+ (id)keyPathsForValuesAffectingCanGoNext;
+ (BOOL)skipStepForContext:(id)arg1 assistantDirection:(int)arg2;
@property __weak NSLayoutConstraint *centeredViewHeightConstraint; // @synthesize centeredViewHeightConstraint=_centeredViewHeightConstraint;
- (void)learnMore:(id)arg1;
- (BOOL)canGoNext;
- (id)nextButtonTitle;
- (id)title;
- (void)viewDidLoad;

@end

