//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEViewController.h>

@class NSImageView, NSString;

@interface IDEDistributionResultSuccessViewController : IDEViewController
{
    NSString *_message;
    NSImageView *_successImageView;
}

@property(retain) NSImageView *successImageView; // @synthesize successImageView=_successImageView;
@property(copy) NSString *message; // @synthesize message=_message;
- (void)loadView;
- (id)nibName;

@end

