//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDESplitViewDebugArea.h>

#import "DVTReplacementViewDelegate-Protocol.h"
#import "DVTSplitViewDelegate-Protocol.h"
#import "DVTStatefulObject-Protocol.h"

@class DVTExtension, DVTObservingToken, IDEConsoleArea, NSString;

@interface IDEDefaultDebugArea : IDESplitViewDebugArea <DVTReplacementViewDelegate, DVTSplitViewDelegate, DVTStatefulObject>
{
    DVTExtension *_currentConsoleExtension;
    DVTExtension *_currentVariablesViewExtension;
    DVTObservingToken *_launchSessionObserver;
    BOOL _shouldOnlyAllowConsole;
}

@property(nonatomic) BOOL shouldOnlyAllowConsole; // @synthesize shouldOnlyAllowConsole=_shouldOnlyAllowConsole;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
@property(readonly) IDEConsoleArea *consoleArea;
- (void)_launchSessionChanged:(id)arg1;
@property(retain) DVTExtension *currentConsoleExtension; // @dynamic currentConsoleExtension;
- (void)_cancelAndNilOutObservers;
- (void)primitiveInvalidate;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)activateConsole;
- (BOOL)canActivateConsole;
- (void)reloadConsole;
- (BOOL)canReloadConsole;
- (void)clearConsole;
- (BOOL)canClearConsole;
- (id)stateSavingIdentifier;
- (id)toolTipForHideRightViewButton;
- (id)toolTipForShowRightViewButton;
- (id)toolTipForHideLeftViewButton;
- (id)toolTipForShowLeftViewButton;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

