//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEActivityReporter.h>

@class DVTObservingToken, IDEActivityReport, NSObject<IDELocalizationWorkProgress>;

@interface IDELocalizationActivityReporter : IDEActivityReporter
{
    NSObject *_worker;
    DVTObservingToken *_localizationStartObserver;
    DVTObservingToken *_localizationPhaseObserver;
    DVTObservingToken *_localizationProgressObserver;
    DVTObservingToken *_localizationCompleteObserver;
    IDEActivityReport *_activeReport;
}

+ (id)_titleSegmentsForWorker:(id)arg1;
+ (void)initialize;
- (void)primitiveInvalidate;
- (void)setWorker:(id)arg1;
- (id)initWithWorkspace:(id)arg1;

@end

