//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEExplorationContext.h>

@interface IDENoteExplorationContext : IDEExplorationContext
{
    id  _note;
}

@property(readonly) id  note; // @synthesize note=_note;
- (int)explorationType;
- (id)initWithNote:(id)arg1;

@end

