//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTOpenQuicklyPattern, IDEOpenQuicklyContext, IDEWorkspace, NSArray, NSMutableArray;

@interface IDEOpenQuicklyMatchProvider : NSObject
{
    IDEOpenQuicklyContext *_context;
    NSMutableArray *_matches;
}

+ (BOOL)enabled;
@property(copy, nonatomic) NSArray *matches; // @synthesize matches=_matches;
@property(retain) IDEOpenQuicklyContext *context; // @synthesize context=_context;
@property(readonly, getter=isIdle) BOOL idle;
- (void)finishCalculatingMatches;
- (void)contextDidChange;
- (void)startCalculatingMatches;
- (void)addMatches:(id)arg1;
@property(readonly) DVTOpenQuicklyPattern *pattern;
@property(readonly) IDEWorkspace *workspace;
- (id)initWithSearchContext:(id)arg1;

@end

