//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDEViewController.h>

#import "IDEProvisioningProfilesViewControllerDelegate-Protocol.h"
#import "IDEProvisioningSigningIdentitiesViewControllerDelegate-Protocol.h"

@class DVTDeveloperAccount, DVTDispatchLock, DVTNotificationToken, IDEProvisioningProfilesViewController, IDEProvisioningSigningIdentitiesViewController, IDEProvisioningSnapshot, NSButton, NSDate, NSMutableSet, NSOperationQueue, NSSet, NSString;

@interface IDEProvisioningTeamDetailsViewController : IDEViewController <IDEProvisioningProfilesViewControllerDelegate, IDEProvisioningSigningIdentitiesViewControllerDelegate>
{
    DVTDispatchLock *_watchForInstallLock;
    NSMutableSet *_watchProfilesForInstall;
    NSMutableSet *_watchCertificateKindsForInstall;
    NSSet *_downloadAllProfilesToWatch;
    struct DVTPortalOperationToken *_token;
    DVTNotificationToken *_profileChangeNoteToken;
    DVTNotificationToken *_identityChangeNoteToken;
    NSOperationQueue *_changeQueue;
    NSDate *_lastRefreshDate;
    DVTDeveloperAccount *_account;
    id  _team;
    IDEProvisioningSnapshot *_provisioningSnapshot;
    IDEProvisioningProfilesViewController *_provisioningProfilesViewController;
    IDEProvisioningSigningIdentitiesViewController *_signingIdentitiesViewController;
    NSButton *_downloadAllButton;
    long long _outstandingDownloadsCount;
}

@property(nonatomic) long long outstandingDownloadsCount; // @synthesize outstandingDownloadsCount=_outstandingDownloadsCount;
@property(retain, nonatomic) NSButton *downloadAllButton; // @synthesize downloadAllButton=_downloadAllButton;
@property(retain, nonatomic) IDEProvisioningSigningIdentitiesViewController *signingIdentitiesViewController; // @synthesize signingIdentitiesViewController=_signingIdentitiesViewController;
@property(retain, nonatomic) IDEProvisioningProfilesViewController *provisioningProfilesViewController; // @synthesize provisioningProfilesViewController=_provisioningProfilesViewController;
@property(retain, nonatomic) IDEProvisioningSnapshot *provisioningSnapshot; // @synthesize provisioningSnapshot=_provisioningSnapshot;
@property(retain, nonatomic) id  team; // @synthesize team=_team;
@property(retain, nonatomic) DVTDeveloperAccount *account; // @synthesize account=_account;
- (BOOL)_tryResolutionOption:(id)arg1 error:(id *)arg2;
- (BOOL)_resetSigningIdentity:(id)arg1 error:(id *)arg2;
- (BOOL)_createSigningIdentity:(id)arg1 error:(id *)arg2;
- (void)_watchForInstallOfSigningIdentity:(id)arg1;
- (void)_certificateKindsModifiedInSnapshotUpdate:(id)arg1 oldIdentities:(id)arg2;
- (void)_didEndProcessingSigningIdentity:(id)arg1;
- (void)_didBeginProcessingSigningIdentity:(id)arg1;
- (void)_signingIdentityBackgroundOperationCommonWithSigningIdentity:(id)arg1 workBlock:(dispatch_block_t)arg2;
- (struct DVTPortalOperationToken *)_token:(id *)arg1;
- (void)_didFinishDownloadingProfiles:(struct NSSet *)arg1;
- (void)_didBeginDownloadingProfiles:(struct NSSet *)arg1;
- (void)_didFinishDownloadAll;
- (void)_stopWatchingForInstallsOfProfiles:(struct NSSet *)arg1;
- (void)_watchForInstallsOfProfiles:(struct NSSet *)arg1;
- (void)_profilesModifiedInSnapshotUpdate:(struct NSSet *)arg1;
- (void)_beginDownloadAllWithProfiles:(struct NSSet *)arg1;
- (void)_downloadProfilesAndHandleErrors:(struct NSSet *)arg1;
- (void)profilesViewController:(id)arg1 updateProfiles:(struct NSSet *)arg2;
- (void)profilesViewController:(id)arg1 downloadProfiles:(struct NSSet *)arg2;
- (void)signingIdentitiesViewController:(id)arg1 exportSigningIdentity:(id)arg2;
- (void)signingIdentitiesViewController:(id)arg1 resetSigningIdentity:(id)arg2;
- (void)signingIdentitiesViewController:(id)arg1 createSigningIdentity:(id)arg2;
- (BOOL)signingIdentitiesViewController:(id)arg1 authorizedToManageIdentity:(id)arg2;
- (void)downloadAllProfiles:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (id)_logAspect;
- (id)_changeQueue;
- (void)_handleFailure:(id)arg1;
- (id)_profilesForDisplay:(id)arg1;
- (void)_performFullUpdateOnQueue:(id)arg1 updateBlock:(dispatch_block_t)arg2;
- (void)_provisioningSnapshotDidUpdate:(id)arg1 oldSnapshot:(id)arg2;
- (void)_updateCommonWithNewSnapshot:(id)arg1 oldSnapshot:(id)arg2 updateBlock:(dispatch_block_t)arg3;
- (void)_registerForChangeNotesOnQueue:(id)arg1 updateBlock:(dispatch_block_t)arg2;
- (void)_bootstrapWithUpdateBlock:(dispatch_block_t)arg1;
- (void)beginWithAccount:(id)arg1 team:(id)arg2;
- (void)primitiveInvalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

