//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import "DVTViewController-Protocol.h"

#import "DVTReplacementViewDelegate-Protocol.h"

@class ABAddressBook, ABPerson, DVTBorderedView, DVTReplacementView, IDEPeoplePickerContentViewController, NSButton, NSImageView, NSString, NSView;

@interface IDEPeoplePickerPopUpContentController : DVTViewController <DVTReplacementViewDelegate>
{
    DVTReplacementView *_replacementView;
    DVTBorderedView *_mainView;
    NSButton *_chooseButton;
    NSButton *_secondaryButton;
    NSButton *_primaryButton;
    BOOL _showingExisting;
    BOOL _usingTemporaryPerson;
    BOOL _didPickExisting;
    BOOL _madeChange;
    ABAddressBook *_addressBook;
    ABPerson *_selectedPerson;
    IDEPeoplePickerContentViewController *_currentVC;
    BOOL _pickingPerson;
    NSImageView *_replacementImageView;
    BOOL _animationInProgress;
    NSView *_nextKeyView;
    id  _delegate;
}

+ (id)defaultViewNibName;
@property(retain) IDEPeoplePickerContentViewController *currentVC; // @synthesize currentVC=_currentVC;
@property(readonly) BOOL showingExisting; // @synthesize showingExisting=_showingExisting;
@property(readonly) BOOL pickingPerson; // @synthesize pickingPerson=_pickingPerson;
@property(readonly) ABPerson *selectedPerson; // @synthesize selectedPerson=_selectedPerson;
@property __weak id  delegate; // @synthesize delegate=_delegate;
- (void)primitiveInvalidate;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)_cleanUpAnimationForView:(id)arg1;
- (void)_setUpAnimationImageViewWithDirection:(double)arg1 actionBlock:(dispatch_block_t)arg2;
- (void)_addAnimationForKey:(id)arg1 toView:(id)arg2;
- (void)_setAnimationDuration;
- (void)done:(id)arg1;
- (void)cancel:(id)arg1;
- (void)chooseExisting:(id)arg1;
- (void)teardown;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
@property(retain) NSString *selectedPersonIdentifier;
- (void)viewDidInstall;
- (void)_resetButtons;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

