//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class IDEProvisioningProfilesViewController, NSSet;

@protocol IDEProvisioningProfilesViewControllerDelegate <NSObject>
- (void)profilesViewController:(IDEProvisioningProfilesViewController *)arg1 updateProfiles:(NSSet *)arg2;
- (void)profilesViewController:(IDEProvisioningProfilesViewController *)arg1 downloadProfiles:(NSSet *)arg2;
@end

