//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEKit/IDESwiftMigrationTargetChooserItem.h>

@class IDESwiftMigrationAssistantContext;

@interface IDESwiftMigrationTargetChooserFolderItem : IDESwiftMigrationTargetChooserItem
{
    IDESwiftMigrationAssistantContext *_assistantContext;
}

+ (id)keyPathsForValuesAffectingState;
@property __weak IDESwiftMigrationAssistantContext *assistantContext; // @synthesize assistantContext=_assistantContext;
- (double)rowHeight;
- (id)warningMessage;
- (id)iconImage;
- (long long)state;
- (void)setState:(long long)arg1;
- (BOOL)isEnabled;
- (id)subtitle;
- (id)title;

@end

