//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "IDESourceControlBranchChooserItemDelegate-Protocol.h"
#import "IDESourceControlWindowController-Protocol.h"

@class IDESourceControlBranchChooserItem, IDESourceControlOperationInfo<IDESourceControlBranchingOperationInfoProtocol>, IDESourceControlWorkspaceUIHandler, IDEWorkspace, NSButton, NSPopUpButton, NSString, NSTextField, NSView, NSWindow;

@interface IDESourceControlBranchChooserWindowController : NSWindowController <IDESourceControlWindowController, IDESourceControlBranchChooserItemDelegate>
{
    NSPopUpButton *_popupButton;
    NSButton *_chooseButton;
    NSTextField *_messageTextField;
    NSView *_newBranchArea;
    NSView *_newBranchSetupView;
    NSTextField *_newBranchNameTextField;
    IDEWorkspace *_workspace;
    IDESourceControlOperationInfo *_operationInfo;
    dispatch_block_t _continuationBlock;
    NSWindow *_parentWindow;
    id  _token;
    BOOL _inProgress;
    NSString *_userNewBranchName;
    BOOL _shouldCreateNewBranch;
    IDESourceControlBranchChooserItem *_chooserItem;
    IDESourceControlWorkspaceUIHandler *_workspaceUIHandler;
}

+ (id)keyPathsForValuesAffectingCanContinue;
@property BOOL shouldCreateNewBranch; // @synthesize shouldCreateNewBranch=_shouldCreateNewBranch;
@property(retain) NSString *userNewBranchName; // @synthesize userNewBranchName=_userNewBranchName;
@property __weak IDESourceControlWorkspaceUIHandler *workspaceUIHandler; // @synthesize workspaceUIHandler=_workspaceUIHandler;
@property(retain) IDESourceControlBranchChooserItem *chooserItem; // @synthesize chooserItem=_chooserItem;
@property BOOL inProgress; // @synthesize inProgress=_inProgress;
@property(copy) dispatch_block_t continuationBlock; // @synthesize continuationBlock=_continuationBlock;
@property(retain) IDESourceControlOperationInfo *operationInfo; // @synthesize operationInfo=_operationInfo;
@property(retain) IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)endSheet;
- (void)cancel:(id)arg1;
- (void)cancelSheet;
- (void)choose:(id)arg1;
- (void)branchChooserSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (BOOL)validateMenuItem:(id)arg1;
- (void)selectBranch:(id)arg1;
- (void)fetchBranches;
@property(readonly) BOOL canContinue;
- (void)hideNewBranchChooser:(id)arg1;
- (void)showNewBranchChooser:(id)arg1;
- (void)displayError:(id)arg1;
- (void)beginSheetForWindow:(id)arg1;
- (id)windowNibName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

