//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTSourceControlAuthenticationFailureHandler-Protocol.h"

@class IDESourceControlCertificateAuthenticator, NSDate, NSString;

@interface IDESourceControlUIHandler : NSObject <DVTSourceControlAuthenticationFailureHandler>
{
    IDESourceControlCertificateAuthenticator *_authenticator;
    NSDate *_timeDeactivated;
    NSString *_showingHostIdentityConfirmationIP;
}

+ (void)showAuthenticationAlertOnWindow:(id)arg1 account:(id)arg2 URL:(id)arg3 completionBlock:(dispatch_block_t)arg4;
+ (BOOL)haveAuthenticationCompletionBlockForURL:(id)arg1;
+ (void)addAuthenticationCompletionBlock:(dispatch_block_t)arg1 forURL:(id)arg2;
+ (id)authenticationCompletionBlocksForURL:(id)arg1;
+ (void)clearAuthenticationCompletionBlocksForURL:(id)arg1;
+ (id)authenticationCompletionBlocks;
+ (void)showFingerprintAlertOnWindow:(id)arg1 host:(id)arg2 fingerprint:(id)arg3 completionBlock:(dispatch_block_t)arg4;
+ (BOOL)haveFingerprintCompletionBlockForHost:(id)arg1;
+ (void)addFingerprintCompletionBlock:(dispatch_block_t)arg1 forHost:(id)arg2;
+ (id)fingerprintCompletionBlocksForHost:(id)arg1;
+ (void)clearFingerprintCompletionBlocksForHost:(id)arg1;
+ (id)fingerprintCompletionBlocks;
+ (void)rejectFingerprintFromHost:(id)arg1;
+ (BOOL)didRejectFingerprintFromHost:(id)arg1;
+ (id)rejectedFingerprintHosts;
+ (void)showCertificateAlertOnWindow:(id)arg1 URL:(id)arg2 completionBlock:(dispatch_block_t)arg3;
+ (BOOL)haveCertificateCompletionBlockForURL:(id)arg1;
+ (void)addCertificateCompletionBlock:(dispatch_block_t)arg1 forURL:(id)arg2;
+ (id)certificateCompletionBlocksForURL:(id)arg1;
+ (void)clearCertificateCompletionBlocksForURL:(id)arg1;
+ (id)certificateCompletionBlocks;
+ (void)rejectCertificateFromURL:(id)arg1;
+ (BOOL)didRejectCertificateFromURL:(id)arg1;
+ (id)rejectedCertificateURLs;
- (void)showHostIdentityConfirmationNotification:(id)arg1;
- (void)showCertificatePanelNotification:(id)arg1;
- (void)sourceControlEnabled:(id)arg1;
- (void)applicationDidDeactivate:(id)arg1;
- (void)applicationDidActivate:(id)arg1;
- (void)askToScanWorkspaceNotification:(id)arg1;
- (void)authenticationNeededNotification:(id)arg1;
- (void)handleAuthenticationFailure:(id)arg1 forRepository:(id)arg2 context:(id)arg3 completionBlock:(dispatch_block_t)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

