//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "IDEComparisonEditorDataSource-Protocol.h"

@class NSString;

@interface IDESourceControlCommitViewerComparisonEditorDataSource : NSObject <IDEComparisonEditorDataSource>
{
}

- (id)documentForSecondaryDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (id)documentForPrimaryDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (void)_cachedDocumentForDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (id)secondaryDocumentLocationForNavigableItem:(id)arg1;
- (id)primaryDocumentLocationForNavigableItem:(id)arg1;
- (id)navigableItemsForSecondaryDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;
- (id)navigableItemsForPrimaryDocumentLocation:(id)arg1 completionBlock:(dispatch_block_t)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

