//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"


@class NSString;

@interface IDETestReportActivityRemoteScreenShotHelper : NSObject <NSURLSessionDownloadDelegate>
{
    dispatch_block_t _progressBlock;
    id  _activity;
    id  _test;
}

- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(dispatch_block_t)arg4;
- (void)downloadRemoteAsset:(id)arg1 forActivity:(id)arg2 test:(id)arg3 progressBlock:(dispatch_block_t)arg4;
- (void)copyDownloadedRemoteAssetFromTmpLocation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

