//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface IDETestReportResultsColors : NSObject
{
}

+ (id)click_greenBarColor;
+ (id)hover_greenBarColor;
+ (id)greenBarColor;
+ (id)click_redBarColor;
+ (id)hover_redBarColor;
+ (id)redBarColor;
+ (id)yellowIssueColor;
+ (id)perfIterationResultCircleColor;
+ (id)baselineBarColor;
+ (id)colorFromUserDefaults:(id)arg1;
+ (void)initialize;

@end

