//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDELocalizationStream.h>

@interface _IDELocalizationStreamBlockBased : IDELocalizationStream
{
    dispatch_block_t _onNextBlock;
    dispatch_block_t _onErrorBlock;
    dispatch_block_t _onCompletedBlock;
}

@property(copy) dispatch_block_t onCompletedBlock; // @synthesize onCompletedBlock=_onCompletedBlock;
@property(copy) dispatch_block_t onErrorBlock; // @synthesize onErrorBlock=_onErrorBlock;
@property(copy) dispatch_block_t onNextBlock; // @synthesize onNextBlock=_onNextBlock;
- (void)onCompleted;
- (void)onError:(id)arg1;
- (void)onNext:(id)arg1;
- (id)initWithOnNextBlock:(dispatch_block_t)arg1 onErrorBlock:(dispatch_block_t)arg2 onCompletedBlock:(dispatch_block_t)arg3;

@end

