//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface IDEAbstractProductType : NSObject
{
}

+ (BOOL)productTypeIdentifierIsWatch1Extension:(id)arg1;
+ (BOOL)productTypeIdentifierIsWatch2Extension:(id)arg1;
+ (BOOL)productTypeIdentifierIsWatch1Application:(id)arg1;
+ (BOOL)productTypeIdentifierIsWatch2Application:(id)arg1;
+ (BOOL)productTypeIdentifierIsWatchExtension:(id)arg1;
+ (BOOL)productTypeIdentifierIsWatchApp:(id)arg1;

@end

