//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTFilePath, NSNumber, NSString;

@interface IDECodeModule : NSObject
{
    NSString *_frameworkNameIncludingExtension;
    BOOL _isInBuiltProductDirectories;
    int _debugSymbolsLoadState;
    NSNumber *_timestamp;
    DVTFilePath *_filePath;
    NSString *_identifier;
    unsigned long long _address;
}

+ (id)keyPathsForValuesAffectingPath;
+ (id)keyPathsForValuesAffectingTimestamp;
+ (id)keyPathsForValuesAffectingName;
+ (id)frameworkNameIncludingExtensionFromPath:(id)arg1;
+ (id)logAspect;
@property(nonatomic) int debugSymbolsLoadState; // @synthesize debugSymbolsLoadState=_debugSymbolsLoadState;
@property(nonatomic) BOOL isInBuiltProductDirectories; // @synthesize isInBuiltProductDirectories=_isInBuiltProductDirectories;
@property(nonatomic) unsigned long long address; // @synthesize address=_address;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(readonly, nonatomic) NSString *path;
@property(readonly, nonatomic) NSString *displayAddress;
@property(readonly, nonatomic) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) NSString *frameworkNameIncludingExtension;
@property(readonly, nonatomic) NSString *name;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 pathString:(id)arg2;
- (id)init;

@end

