//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDEDistributionStep.h>

@interface IDEDistributionSummaryStep : IDEDistributionStep
{
}

+ (id)_platformsRequiringBitcodeWithAppStoreSubmissionConfiguration:(id)arg1 flattenedDistributionItems:(id)arg2 error:(id *)arg3;
+ (id)_platformsWantingBitcodeAskWithAppStoreSubmissionConfiguration:(id)arg1 flattenedDistributionItems:(id)arg2 error:(id *)arg3;
+ (id)availableOptionsForPropertyList;
- (id)platformsRequiringBitcodeForDistributionItemsWithError:(id *)arg1;
- (id)platformsWantingBitcodeAskWithError:(id *)arg1;
@property(readonly) BOOL requiresBitcode;
@property(readonly) BOOL wantsCompileBitcodeAsk;
@property(readonly) BOOL wantsSymbolCollectionAsk;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;
- (BOOL)loadFromPropertyList:(id)arg1 error:(id *)arg2;

@end

