//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDEDistributionStep.h>

@interface IDEDistributionSigningAssetsStep : IDEDistributionStep
{
}

+ (id)availableOptionsForPropertyList;
+ (id)archivedTeamIDForFlattenedDistributionItems:(id)arg1;
- (BOOL)populateProvisioningSnapshotWithError:(id *)arg1;
- (BOOL)populateTopLevelDistributionItemsIfNecessaryWithError:(id *)arg1;
- (id)providedOutputContextPropertyNames;
- (id)requiredInputContextPropertyNames;
- (BOOL)loadFromPropertyList:(id)arg1 error:(id *)arg2;

@end

