//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSString;

@interface IDEDistributionManifest : NSObject
{
    NSString *_name;
    NSString *_bundleIdentifier;
    NSString *_bundleVersion;
    NSString *_appURL;
    NSString *_displayImageURL;
    NSString *_fullSizeImageURL;
    NSString *_assetPackManifestURL;
}

@property(retain) NSString *assetPackManifestURL; // @synthesize assetPackManifestURL=_assetPackManifestURL;
@property(retain) NSString *fullSizeImageURL; // @synthesize fullSizeImageURL=_fullSizeImageURL;
@property(retain) NSString *displayImageURL; // @synthesize displayImageURL=_displayImageURL;
@property(retain) NSString *appURL; // @synthesize appURL=_appURL;
@property(retain) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(retain) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain) NSString *name; // @synthesize name=_name;
- (id)dictionaryRepresentationForVariants:(id)arg1 error:(id *)arg2;
- (BOOL)isValidManifest;
- (BOOL)validateAssetPackManifestURL:(id *)arg1 error:(id *)arg2;
- (BOOL)validateFullSizeImageURL:(id *)arg1 error:(id *)arg2;
- (BOOL)validateDisplayImageURL:(id *)arg1 error:(id *)arg2;
- (BOOL)validateAppURL:(id *)arg1 error:(id *)arg2;
- (BOOL)_validateURL:(id)arg1 propertyName:(id)arg2 error:(id *)arg3;

@end

