//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class IDEBreakpoint, NSArray;

@protocol IDEInternalBreakpointDelegate <NSObject>

@optional
- (void)internal_breakpointLocationsAdded:(NSArray *)arg1 removed:(NSArray *)arg2;
- (void)internal_breakpointEnablementChanged:(IDEBreakpoint *)arg1;
@end

