//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDELocalizationWorkContext.h>

@class IDEContainer<IDELocalizedContainer>, NSURL, NSXMLDocument;

@interface IDELocalizationLanguageImportContext : IDELocalizationWorkContext
{
    NSURL *_sourceUrl;
    IDEContainer *_container;
    NSXMLDocument *_importXLIFF;
}

+ (id)contextWithParent:(id)arg1 sourceUrl:(id)arg2 container:(id)arg3 importXLIFF:(id)arg4;
@property(retain) NSXMLDocument *importXLIFF; // @synthesize importXLIFF=_importXLIFF;
@property(retain) IDEContainer *container; // @synthesize container=_container;
@property(retain) NSURL *sourceUrl; // @synthesize sourceUrl=_sourceUrl;
- (void)primitiveInvalidate;

@end

