//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <IDEFoundation/IDELocalizationWorkContext.h>

#import "IDELocalizationWorkProvider-Protocol.h"

@class IDEContainer<IDELocalizedContainer>, NSArray, NSString, NSURL;

@interface IDELocalizationBundleExportContext : IDELocalizationWorkContext <IDELocalizationWorkProvider>
{
    NSURL *_destinationUrl;
    IDEContainer *_container;
    NSString *_sourceLanguage;
    NSArray *_targetLanguages;
}

+ (id)contextWithParent:(id)arg1 destinationUrl:(id)arg2 container:(id)arg3 sourceLanguage:(id)arg4 targetLanguages:(id)arg5;
@property(retain) NSArray *targetLanguages; // @synthesize targetLanguages=_targetLanguages;
@property(retain) NSString *sourceLanguage; // @synthesize sourceLanguage=_sourceLanguage;
@property(retain) IDEContainer *container; // @synthesize container=_container;
@property(retain) NSURL *destinationUrl; // @synthesize destinationUrl=_destinationUrl;
- (id)work;
- (void)primitiveInvalidate;

@end

