//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "ITunesSoftwareServiceConfigurationResponse-Protocol.h"

@class NSArray, NSDictionary, NSString;

@interface IDENoNetworkConfigurationResponse : NSObject <ITunesSoftwareServiceConfigurationResponse>
{
    BOOL _isSuccessful;
    BOOL _isCancelled;
    NSDictionary *_configuration;
    NSString *_alertMessage;
    NSArray *_errors;
    NSArray *_warnings;
    NSArray *_infoMessages;
}

@property(readonly) NSArray *infoMessages; // @synthesize infoMessages=_infoMessages;
@property(readonly) NSArray *warnings; // @synthesize warnings=_warnings;
@property(readonly) NSArray *errors; // @synthesize errors=_errors;
@property(readonly) NSString *alertMessage; // @synthesize alertMessage=_alertMessage;
@property(readonly) NSDictionary *configuration; // @synthesize configuration=_configuration;
@property(readonly) BOOL isCancelled; // @synthesize isCancelled=_isCancelled;
@property(readonly) BOOL isSuccessful; // @synthesize isSuccessful=_isSuccessful;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

