//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTInvalidation-Protocol.h"

@class DVTFilePath, DVTObservingToken, DVTStackBacktrace, IDEPlaygroundCommonSharedContext, NSDate, NSDictionary, NSSet, NSString;

@interface IDEPlaygroundAuxiliarySourceMonitor : NSObject <DVTInvalidation>
{
    IDEPlaygroundCommonSharedContext *_context;
    IDEPlaygroundAuxiliarySourceMonitor *_dependency;
    NSDate *_lastModificationDate;
    NSSet *_sourcesDirectorySwiftFiles;
    DVTFilePath *__monitoredSourcesDirectory;
    DVTObservingToken *__sourcesDirectoryObserverToken;
    DVTObservingToken *__dependencyModificationObserverToken;
    NSDictionary *__sourcesFileContentsHashes;
}

+ (void)initialize;
@property(retain, nonatomic) NSDictionary *_sourcesFileContentsHashes; // @synthesize _sourcesFileContentsHashes=__sourcesFileContentsHashes;
@property(retain, nonatomic) DVTObservingToken *_dependencyModificationObserverToken; // @synthesize _dependencyModificationObserverToken=__dependencyModificationObserverToken;
@property(retain, nonatomic) DVTObservingToken *_sourcesDirectoryObserverToken; // @synthesize _sourcesDirectoryObserverToken=__sourcesDirectoryObserverToken;
@property(retain, nonatomic, setter=_setMonitoredSourcesDirectory:) DVTFilePath *_monitoredSourcesDirectory; // @synthesize _monitoredSourcesDirectory=__monitoredSourcesDirectory;
@property(copy, nonatomic) NSSet *sourcesDirectorySwiftFiles; // @synthesize sourcesDirectorySwiftFiles=_sourcesDirectorySwiftFiles;
@property(retain, nonatomic) NSDate *lastModificationDate; // @synthesize lastModificationDate=_lastModificationDate;
@property(readonly) __weak IDEPlaygroundAuxiliarySourceMonitor *dependency; // @synthesize dependency=_dependency;
@property(readonly, nonatomic) IDEPlaygroundCommonSharedContext *context; // @synthesize context=_context;
- (void)_populateSourcesDirectorySwiftFiles;
- (void)primitiveInvalidate;
- (id)initWithPlaygroundContext:(id)arg1 dependency:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

