//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSArray, NSData, NSDate, NSMutableArray, NSString, NSUUID, XCSynthesizedEventRecord;

@interface IDESchemeActionTestActivitySummary : NSObject
{
    NSData *_screenshotData;
    NSData *_snapshotData;
    NSData *_elementsOfInterestData;
    NSData *_synthesizedEventData;
    NSString *_title;
    NSUUID *_uuid;
    NSDate *_start;
    NSDate *_finish;
    NSMutableArray *_subActivities;
    NSString *_screenshotFileName;
    NSString *_snapshotFileName;
    NSString *_elementsOfInterestFileName;
    NSString *_synthesizedEventFileName;
}

+ (id)summariesFromSummaries:(id)arg1 withAttachmentsExtractedToDirectory:(id)arg2;
@property(readonly, copy) NSString *synthesizedEventFileName; // @synthesize synthesizedEventFileName=_synthesizedEventFileName;
@property(readonly, copy) NSString *elementsOfInterestFileName; // @synthesize elementsOfInterestFileName=_elementsOfInterestFileName;
@property(readonly, copy) NSString *snapshotFileName; // @synthesize snapshotFileName=_snapshotFileName;
@property(readonly, copy) NSString *screenshotFileName; // @synthesize screenshotFileName=_screenshotFileName;
@property(copy) NSMutableArray *subActivities; // @synthesize subActivities=_subActivities;
@property(readonly, copy) NSData *snapshotData; // @synthesize snapshotData=_snapshotData;
@property(readonly, copy) NSData *screenshotData; // @synthesize screenshotData=_screenshotData;
@property(readonly, copy) NSDate *finish; // @synthesize finish=_finish;
@property(readonly, copy) NSDate *start; // @synthesize start=_start;
@property(readonly, copy) NSUUID *uuid; // @synthesize uuid=_uuid;
@property(readonly, copy) NSString *title; // @synthesize title=_title;
@property(readonly) struct CGRect subregionOfInterest;
@property(readonly) XCSynthesizedEventRecord *synthesizedEvent;
@property(readonly, copy) NSArray *elementsOfInterest;
- (BOOL)isEqualToTestActivitySummary:(id)arg1;
- (void)addSubActivity:(id)arg1;
- (void)updateFromActivityRecord:(id)arg1;
- (void)loadAttachmentsFromDirectory:(id)arg1;
- (id)dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithActivityRecord:(id)arg1;

@end

