//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSMutableDictionary;

@interface IDETestBaselineRecord : NSObject
{
    NSMutableDictionary *_performanceMetricIdentifiersDict;
    NSMutableDictionary *_classNamesDict;
}

+ (void)initialize;
- (void)applyBaselineRecord:(id)arg1 usingBehavior:(unsigned long long)arg2;
- (void)applyBaselineRecord:(id)arg1 usingBehavior:(unsigned long long)arg2 testClassName:(id)arg3 testMethodName:(id)arg4;
- (void)unionWithDefaultsInBaselineRecord:(id)arg1;
- (void)removeBaselinesForTestClassName:(id)arg1 testMethodName:(id)arg2 performanceMetricIdentifier:(id)arg3;
- (void)removeBaselinesForTestClassName:(id)arg1 testMethodName:(id)arg2;
- (void)removeBaselinesForTestClassName:(id)arg1;
- (void)setBaselineForTestClassName:(id)arg1 testMethodName:(id)arg2 performanceMetricIdentifier:(id)arg3 maxPercentRegression:(id)arg4 maxPercentImprovement:(id)arg5 maxPercentRelativeStandardDeviation:(id)arg6 maxRegression:(id)arg7 maxStandardDeviation:(id)arg8;
- (void)setBaselineForTestClassName:(id)arg1 testMethodName:(id)arg2 performanceMetricIdentifier:(id)arg3 baselineDisplayName:(id)arg4 average:(id)arg5 maxPercentRegression:(id)arg6 maxPercentImprovement:(id)arg7 maxPercentRelativeStandardDeviation:(id)arg8 maxRegression:(id)arg9 maxStandardDeviation:(id)arg10;
- (void)_setBaselineForTestClassName:(id)arg1 testMethodName:(id)arg2 performanceMetricIdentifier:(id)arg3 baselineDisplayName:(id)arg4 average:(id)arg5 maxPercentRegression:(id)arg6 maxPercentImprovement:(id)arg7 maxPercentRelativeStandardDeviation:(id)arg8 maxRegression:(id)arg9 maxStandardDeviation:(id)arg10;
- (id)baselineForTestClassName:(id)arg1 testMethodName:(id)arg2 performanceMetricIdentifier:(id)arg3;
- (void)setDefaultBaselineForPerformanceMetricIdentifier:(id)arg1 maxPercentRegression:(id)arg2 maxPercentImprovement:(id)arg3 maxPercentRelativeStandardDeviation:(id)arg4 maxRegression:(id)arg5 maxStandardDeviation:(id)arg6;
- (id)defaultBaselineForPerformanceMetricIdentifier:(id)arg1;
- (id)performanceMetricIdentifiersWithDefaultBaseline;
- (id)performanceMetricIdentifiersForClassName:(id)arg1 testMethodName:(id)arg2;
- (id)testMethodNamesForClassName:(id)arg1;
- (id)testClassNames;
- (BOOL)writeToFilePath:(id)arg1 workspace:(id)arg2 versionedFileManager:(id)arg3 error:(id *)arg4;
- (id)_plistDataWithError:(id *)arg1;
- (id)initWithFilePath:(id)arg1 error:(id *)arg2;
- (BOOL)_validatePropertyList:(id)arg1 errorString:(id *)arg2;
- (BOOL)_validateClassNamesDictionary:(id)arg1 locationDescription:(id)arg2 errorString:(id *)arg3;
- (BOOL)_validatePerformanceMetricBaselinesByPerformanceMetricIdentifierDictionary:(id)arg1 locationDescription:(id)arg2 errorString:(id *)arg3;
- (id)init;

@end

