//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <DVTKit/KeyLoopSplicingContainerView.h>


@class DVTTabbedWindowTabViewItem, DVTViewController<DVTTabbedWindowTabContentControlling>, NSArray, NSColor, NSImage, NSString, NSTabView, NSView, NSVisualEffectView, NSWindowController<DVTTabbedWindowControlling>;

@interface DVTBarBackground : KeyLoopSplicingContainerView <NSTabViewDelegate>
{
    BOOL _becomingFirstResponder;
    NSView *_mainContentContainerView;
    NSView *_bottomBorderView;
    NSView *_backdropDarkeningView;
    NSVisualEffectView *_backdropView;
    BOOL _mouseDownCanMoveWindow;
    BOOL _hasTopBorder;
    BOOL _hasBottomBorder;
    BOOL _usesScopeBarAppearance;
    BOOL _usesModernToolbarAppearance;
    BOOL _allowDetachDrags;
    DVTTabbedWindowTabViewItem *_selectedTabViewItem;
    NSColor *_bottomBorderColor;
    NSView *_contentView;
    NSColor *_backgroundColor;
    NSImage *_backgroundImage;
    id  _delegate;
    NSWindowController *_tabbedWindowController;
    NSTabView *_tabView;
}

+ (id)keyPathsForValuesAffectingActiveViewController;
+ (BOOL)isTabDrag:(id)arg1;
@property(nonatomic) __weak NSTabView *tabView; // @synthesize tabView=_tabView;
@property(retain) NSWindowController *tabbedWindowController; // @synthesize tabbedWindowController=_tabbedWindowController;
@property(retain, nonatomic) id  delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL allowDetachDrags; // @synthesize allowDetachDrags=_allowDetachDrags;
@property(retain, nonatomic) NSImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) BOOL usesModernToolbarAppearance; // @synthesize usesModernToolbarAppearance=_usesModernToolbarAppearance;
@property(nonatomic) BOOL usesScopeBarAppearance; // @synthesize usesScopeBarAppearance=_usesScopeBarAppearance;
@property(retain, nonatomic) NSColor *bottomBorderColor; // @synthesize bottomBorderColor=_bottomBorderColor;
@property(nonatomic) BOOL hasBottomBorder; // @synthesize hasBottomBorder=_hasBottomBorder;
@property(nonatomic) BOOL hasTopBorder; // @synthesize hasTopBorder=_hasTopBorder;
@property BOOL mouseDownCanMoveWindow; // @synthesize mouseDownCanMoveWindow=_mouseDownCanMoveWindow;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityAttributeValue:(id)arg1;
- (void)updateLabelNowForTab:(id)arg1;
- (void)updateLabelSoonForTab:(id)arg1;
- (void)updateTabTitlesNow;
- (void)tabTitlesDidChange;
- (void)setReadyToUse;
- (void)disconnectFromTabbedWindowController;
- (struct CGRect)contentFrame;
- (void)_windowChangedKeyState;
- (void)didCollapse;
- (void)willCollapse;
- (void)didExpand;
- (void)willExpand;
- (void)setDefaultKeyLoop;
- (void)_addBackdropDarkeningViewForModernToolbarAppearance;
- (void)_addBottomBorderViewForModernToolbarAppearance;
- (void)_addBackdropViewForModernToolbarAppearance;
- (BOOL)isOpaque;
- (void)drawRect:(struct CGRect)arg1;
- (void)_drawBackgroundInRect:(struct CGRect)arg1;
@property(readonly, nonatomic) double topBorderHeight;
- (void)viewWillStartLiveResize;
- (void)viewDidEndLiveResize;
- (void)tabViewDidChangeNumberOfTabViewItems:(id)arg1;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)tabView:(id)arg1 willSelectTabViewItem:(id)arg2;
- (void)selectTabViewItemAtIndex:(long long)arg1;
- (void)selectTabViewItem:(id)arg1;
@property(readonly, nonatomic) DVTTabbedWindowTabViewItem *selectedTabViewItem; // @synthesize selectedTabViewItem=_selectedTabViewItem;
@property(readonly) NSArray *tabViewItems;
- (void)insertTabViewItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)moveTabViewItem:(id)arg1 toIndex:(unsigned long long)arg2;
- (void)removeTabViewItem:(id)arg1;
- (long long)indexOfTabViewItem:(id)arg1;
- (id)tabViewItemAtIndex:(long long)arg1;
@property(readonly) long long numberOfTabViewItems;
- (id)newTabWithViewController:(id)arg1 atIndex:(unsigned long long)arg2;
@property(readonly) DVTViewController *activeViewController;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)commonInit;
@property(readonly, retain, nonatomic) NSColor *defaultBottomBorderLineColor;
@property(readonly, retain, nonatomic) NSColor *secondTopBorderLineColor;
@property(readonly, retain, nonatomic) NSColor *firstTopBorderLineColor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

