//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <DVTKit/DVTAbstractColorPicker.h>

@class NSDictionary;

@interface DVTColorPickerPopUpButton : DVTAbstractColorPicker
{
    struct CGRect popUpButtonArrowsRect;
    struct CGRect colorWellViewRect;
    struct CGRect colorLabelRect;
    struct CGRect swatchRect;
    struct CGRect colorLabelTitleRect;
    NSDictionary *imageStateDictionary;
}

+ (id)imageStateDictionaryForControlSize:(unsigned long long)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)isMouseEventInColorWellRect:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawColorLabel;
- (void)drawColorWell;
- (void)drawPopUpButtonArrows;
- (void)drawDebuggingRects;
- (void)drawFocusRing;
- (id)effectiveAttributedTitle;
- (id)attributedTitleForTitle:(id)arg1;
- (id)titleAttributes;
- (double)swatchHeight;
- (id)effectiveImageForControlPart:(int)arg1;
- (id)effectivePopUpButtonArrowsRightCapImage;
- (id)effectiveTextColor;
- (struct CGPoint)popUpMenuLocation;
- (double)horizontalMenuOffset;
- (double)verticalMenuOffset;
- (void)sizeRectsForDrawing;
- (double)verticalTitleOffset;
- (double)baseline;
- (double)heightThatFits;
- (double)widthForPopUpButton;
- (CDStruct_bf6d4a14)shadowInset;
- (BOOL)isShowingTitle;
- (struct CGRect)insetRectForSwatchRect:(struct CGRect)arg1;
- (struct CGRect)swatchRectForColorWellRect:(struct CGRect)arg1;
- (void)setControlSize:(unsigned long long)arg1;
- (id)imageStateDictionary;
- (void)invalidateImageStateDictionary;

@end

