//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import "DVTDeviceApplicationProvider-Protocol.h"

@class NSError, NSString;

@protocol DVTDeviceApplicationInstaller <DVTDeviceApplicationProvider>
- (BOOL)uploadApplicationDataWithPath:(NSString *)arg1 forInstalledApplicationWithBundleIdentifier:(NSString *)arg2 error:(id *)arg3;
- (BOOL)downloadApplicationDataToPath:(NSString *)arg1 forInstalledApplicationWithBundleIdentifier:(NSString *)arg2 error:(id *)arg3;
- (NSError *)uninstallApplicationWithBundleIdentifierSync:(NSString *)arg1;
@end

