//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTNotificationToken, NSMetadataQuery;

@interface DVTDevicesDebugInfoFixupCenter : NSObject
{
    NSMetadataQuery *_dsymQuery;
    DVTNotificationToken *_dsymFinishedInitialGatheringToken;
    DVTNotificationToken *_dsymUpdateToken;
}

+ (void)_dSYMFixupFixItem:(id)arg1;
+ (id)_dSYMFixupUuidImporterPath;
+ (id)sharedCenter;
+ (id)logAspect;
- (void)_dSYMFixupQueryDidUpdate:(id)arg1;
- (void)_dSYMFixupQueryDidFinishInitialGathering:(id)arg1;
- (BOOL)_isEnabled;
- (void)stopFixup;
- (void)startFixup;
- (void)dealloc;
- (id)init;

@end

