//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface DVTGradientImageButtonCell : NSButtonCell
{
    BOOL _usedAsRadioButton;
    int _gradientStyle;
    int _borderSides;
}

@property BOOL usedAsRadioButton; // @synthesize usedAsRadioButton=_usedAsRadioButton;
@property int borderSides; // @synthesize borderSides=_borderSides;
@property(nonatomic) int gradientStyle; // @synthesize gradientStyle=_gradientStyle;
- (BOOL)_isTabStyleCell;
- (BOOL)_shouldUseColorPunchOutStyle;
- (void)_setGradientStyle:(int)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setTitle:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (id)initWithGradientStyle:(int)arg1 borderSides:(int)arg2;
- (void)dvt_commonInitWithGradientStyle:(int)arg1 borderSides:(int)arg2;
- (id)accessibilityAttributeValue:(id)arg1;

@end

