//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTComparisonSplitView;

@interface DVTSourceTextScrollView : NSScrollView
{
    id  _delegate;
    DVTComparisonSplitView *_comparisonSplitView;
    BOOL _scrollingHorizontally;
}

+ (BOOL)isCompatibleWithResponsiveScrolling;
@property(retain) DVTComparisonSplitView *comparisonSplitView; // @synthesize comparisonSplitView=_comparisonSplitView;
@property(retain) id  delegate; // @synthesize delegate=_delegate;
- (id)_pointInVisibleScroller:(struct CGPoint)arg1;
- (void)reflectScrolledClipView:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;

@end

