//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <DVTKit/DVTMainStatusAwareButton.h>


@class NSString;

@interface DVTTabBarClippedItemsIndicator : DVTMainStatusAwareButton <NSMenuDelegate>
{
    id _delegate;
}

+ (Class)cellClass;
- (void)_popUpMenu;
- (void)mouseDown:(id)arg1;
- (void)performClick:(id)arg1;
- (void)moveLeft:(id)arg1;
- (void)moveRight:(id)arg1;
- (void)moveUp:(id)arg1;
- (void)moveDown:(id)arg1;
- (BOOL)needsPanelToBecomeKey;
- (id)delegate;
- (void)setDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

