//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSLayoutManager, NSTextContainer, NSTextStorage;

@interface DVTTableCellViewMultiLineTextFieldCell : NSTextFieldCell
{
    NSTextContainer *_textContainer;
    NSLayoutManager *_layoutManager;
    BOOL _replaceNewlinesWithVisibleCharacter;
    NSTextStorage *_textStorage;
    struct _NSRange _rangeToEnsureIsVisible;
}

@property(retain, nonatomic) NSTextStorage *textStorage; // @synthesize textStorage=_textStorage;
@property(nonatomic) struct _NSRange rangeToEnsureIsVisible; // @synthesize rangeToEnsureIsVisible=_rangeToEnsureIsVisible;
@property(nonatomic) BOOL replaceNewlinesWithVisibleCharacter; // @synthesize replaceNewlinesWithVisibleCharacter=_replaceNewlinesWithVisibleCharacter;
- (id)_replaceNewlinesWithVisibleCharacter:(id)arg1;
- (id)_trimLeadingWhitespaceFromString:(id)arg1;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;
- (void)drawWithExpansionFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)_attributesInRange:(struct _NSRange)arg1 inTextStorage:(id)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setBackgroundStyle:(long long)arg1;
- (void)setObjectValue:(id)arg1;
- (void)update;
- (void)_provideTextComponentsGivenTextStorage:(id)arg1 containerSize:(struct CGSize)arg2 handler:(dispatch_block_t)arg3;
- (void)_dvtTableCellViewMultiLineTextFieldCell_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

