//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSUndoTextOperation;

@interface DVTTextStorageCommonUndoHelper : NSObject
{
    NSUndoTextOperation *_undoTextOperation;
    BOOL _isNonUserEdit;
    struct _NSRange _savedSelectedRange;
}

- (void)restoreSelectedRange:(id)arg1;
- (void)saveSelectedRange:(id)arg1;
- (void)didUndoRedo:(id)arg1;
- (void)willUndoRedo:(id)arg1;
- (BOOL)isUserEdit;
- (id)initWithUndoTextOperation:(id)arg1 affectedRange:(struct _NSRange)arg2 layoutManager:(id)arg3 undoManager:(id)arg4 replacementRange:(struct _NSRange)arg5;

@end

