//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class WebView;

@interface DVTWebViewTextAttachmentCell : NSViewTextAttachmentCell
{
    WebView *_webView;
}

@property(retain) WebView *webView; // @synthesize webView=_webView;
- (id)viewWithFrame:(struct CGRect)arg1 forView:(id)arg2 characterIndex:(unsigned long long)arg3 layoutManager:(id)arg4;
- (struct CGSize)cellSize;

@end

