//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface NSWindow (DVTNSWindowExtras)
+ (BOOL)_dvt_shouldZoomOnDoubleClick;
- (id)safari_toolbarBottomEdgeLowerColor;
- (id)safari_contentInsetColor;
- (id)safari_contentSeparatorColor;
- (id)dvt_imageForRect:(struct CGRect)arg1;
- (BOOL)_dvt_hasActiveAppearanceIgnoringKeyFocus;
- (BOOL)_safari_hasActiveAppearanceIgnoringKeyFocus;
- (BOOL)dvt_makeNonDeferred;
- (struct CGImage *)_dvt_createCGImageForRect:(struct CGRect)arg1 excludingChildWindows:(id)arg2;
- (struct CGPoint)safari_convertPointFromScreen:(struct CGPoint)arg1;
- (struct CGPoint)dvt_convertPointFromScreen:(struct CGPoint)arg1;
- (struct CGPoint)safari_convertPointToScreen:(struct CGPoint)arg1;
- (struct CGPoint)dvt_convertPointToScreen:(struct CGPoint)arg1;
@end

