//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTMacroDefinitionConditionSet, NSString;

@interface DVTMacroAssignmentInfo : NSObject
{
    NSString *_macroName;
    id  _value;
    DVTMacroDefinitionConditionSet *_conditionSet;
}

+ (id)newWithMacroName:(id)arg1 value:(id)arg2 conditionSet:(id)arg3;
@property(readonly) DVTMacroDefinitionConditionSet *conditionSet; // @synthesize conditionSet=_conditionSet;
@property(readonly) id  value; // @synthesize value=_value;
@property(readonly) NSString *macroName; // @synthesize macroName=_macroName;
- (id)description;
- (id)initWithMacroName:(id)arg1 value:(id)arg2 conditionSet:(id)arg3;

@end

