//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

#import "DVTCodesignableDevice-Protocol.h"

@class NSSet, NSString;

@interface DVTCodesignableDeviceSnapshot : NSObject <DVTCodesignableDevice>
{
    BOOL _supportsProvisioning;
    NSString *_name;
    NSString *_nameForDeveloperPortal;
    NSString *_identifier;
    NSString *_platformIdentifier;
    NSSet *_proxiedDevices;
}

+ (id)snapshotFromCodesignableDevice:(id)arg1;
@property(copy) NSSet *proxiedDevices; // @synthesize proxiedDevices=_proxiedDevices;
@property BOOL supportsProvisioning; // @synthesize supportsProvisioning=_supportsProvisioning;
@property(copy) NSString *platformIdentifier; // @synthesize platformIdentifier=_platformIdentifier;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
@property(copy) NSString *nameForDeveloperPortal; // @synthesize nameForDeveloperPortal=_nameForDeveloperPortal;
@property(copy) NSString *name; // @synthesize name=_name;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

