//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <DVTFoundation/DVTDispatchLock.h>

@interface DVTDispatchLock_ReadWrite : DVTDispatchLock
{
    void *_context;
}

- (void)performLockedReaderBlock:(dispatch_block_t)arg1;
- (id)initWithDebugName:(id)arg1;

@end

