//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class DVTDispatchLock, DVTObservingToken, NSError, NSMutableArray;

@interface DVTOperation : NSOperation
{
    dispatch_block_t _block;
    NSError *_error;
    DVTDispatchLock *_cancellationRegistrationLock;
    DVTDispatchLock *_cancellationBlockLock;
    NSMutableArray *_cancellationBlockTokens;
    DVTDispatchLock *_finishingLock;
    NSMutableArray *_finishingTokens;
    BOOL _preventFinish;
    DVTObservingToken *_isFinishedObserverToken;
    DVTObservingToken *_isExecutingObserverToken;
}

+ (void)_trackStateChange:(id)arg1 ofOperation:(id)arg2 forKeyPath:(id)arg3;
+ (id)unfinishedOperations;
+ (id)operationWithBlock:(dispatch_block_t)arg1;
@property BOOL preventFinish; // @synthesize preventFinish=_preventFinish;
@property(copy) NSError *error; // @synthesize error=_error;
@property(copy) dispatch_block_t block; // @synthesize block=_block;
- (void)trackFuture:(id)arg1;
- (void)trackFuture:(id)arg1 cancel:(BOOL)arg2 error:(BOOL)arg3;
- (id)notFinishedReasonWithDepth:(unsigned long long)arg1;
- (id)stateString;
- (void)enumerateUsingBlock:(dispatch_block_t)arg1;
- (void)_enumerateWithStop:(char *)arg1 usingBlock:(dispatch_block_t)arg2;
- (void)allowFinishForToken:(id)arg1;
- (id)disallowFinishWithReason:(id)arg1;
- (BOOL)isFinished;
- (void)cancel;
- (BOOL)unregisterCancellationBlockForToken:(id)arg1;
- (id)registerCancellationBlock:(dispatch_block_t)arg1;
- (void)main;
- (id)description;
- (void)dealloc;
- (id)init;

@end

