//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@interface DVTLayoutViewFrameChangeStack : NSObject
{
    struct CGRect _previousFrames[5];
}

- (BOOL)registeredRectsHaveNoNonIntegralChangeCyclesAfterRegisteringRect:(struct CGRect)arg1;

@end

