//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"


@class NSString;

@interface DVTStepperTextField : NSTextField <NSTextViewDelegate>
{
    unsigned long long _scrubberMode;
    BOOL _trulyEditable;
    BOOL _trulySelectable;
    float _v0;
    float _delta;
    BOOL _reachedStage2;
    double _minValue;
    double _maxValue;
    double _increment;
    struct CGRect _rectForPulse;
}

+ (Class)cellClass;
@property BOOL reachedStage2; // @synthesize reachedStage2=_reachedStage2;
@property struct CGRect rectForPulse; // @synthesize rectForPulse=_rectForPulse;
@property double increment; // @synthesize increment=_increment;
@property double maxValue; // @synthesize maxValue=_maxValue;
@property double minValue; // @synthesize minValue=_minValue;
- (void)textDidEndEditing:(id)arg1;
- (void)gestureRecognizerAction:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (BOOL)_eventLocationIsOverMinusOrPlusButton:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)beginMouseDragScrubbingWithEvent:(id)arg1;
- (void)_setValueSendingAction:(double)arg1;
- (void)updateValueWithEvent:(id)arg1;
- (float)checkBounds:(float)arg1;
- (void)resetCursorRects;
- (void)setMode:(unsigned long long)arg1;
- (BOOL)becomeFirstResponder;
- (void)doCommandBySelector:(SEL)arg1;
- (void)_increment;
- (void)_decrement;
- (double)_incrementToUse;
@property(readonly) double defaultIncrement;
- (BOOL)allowsVibrancy;
- (BOOL)isOpaque;
- (void)_setSelectable_transient:(BOOL)arg1;
- (void)setSelectable:(BOOL)arg1;
- (BOOL)_isTrulyEditable;
- (void)_setEditable_transient:(BOOL)arg1;
- (void)setEditable:(BOOL)arg1;
- (void)_dvtStepperTextField_commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

