//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <DVTKit/DVTViewController.h>

@class DVTDevice;

@interface DVTDeviceSummarySliceViewController : DVTViewController
{
    DVTDevice *_device;
}

@property(readonly) DVTDevice *device; // @synthesize device=_device;
- (id)initWithDevice:(id)arg1;

@end

