//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class NSMutableArray;

@interface DVTSegmentedControl : NSSegmentedControl
{
    NSMutableArray *_alternateImages;
    BOOL _shouldDrawMenuIndictor;
    BOOL _bordered;
    double _menuIndicatorInset;
}

+ (id)toolbarSegmentedControlWithImages:(id)arg1 trackingMode:(unsigned long long)arg2;
+ (id)toolbarSegmentedControlWithTrackingMode:(unsigned long long)arg1 images:(id)arg2 alternateImages:(id)arg3;
@property(getter=isBordered) BOOL bordered; // @synthesize bordered=_bordered;
@property double menuIndicatorInset; // @synthesize menuIndicatorInset=_menuIndicatorInset;
@property BOOL shouldDrawMenuIndictor; // @synthesize shouldDrawMenuIndictor=_shouldDrawMenuIndictor;
- (BOOL)wantsDefaultClipping;
- (void)setNeedsDisplay:(BOOL)arg1;
- (void)applyDVTStyleWithTrackingMode:(unsigned long long)arg1;
- (void)setAlternateImage:(id)arg1 forSegment:(long long)arg2;
- (id)alternateImageForSegment:(long long)arg1;
- (id)_getImageInArray:(id)arg1 forSegment:(long long)arg2;
- (void)_setImage:(id)arg1 inArray:(id)arg2 forSegment:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
@property BOOL useAnyDrawingStyle;
@property BOOL useRadioDrawingStyle;
@property BOOL useMenuDelayForSelectedSegment;
@property BOOL useMenuDelay;

@end

