//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"
#import <DVTKit/DVTTableCellView.h>

@class NSLayoutConstraint;

@interface DVTTableCellViewMultiLine : DVTTableCellView
{
    unsigned long long _maxNumberOfTitleLines;
    unsigned long long _maxNumberOfSubtitleLines;
    NSLayoutConstraint *_titleTextFieldHeightConstraint;
    NSLayoutConstraint *_subtitleTextFieldHeightConstraint;
}

+ (double)_textFieldHeightGivenRowCount:(unsigned long long)arg1 font:(id)arg2;
@property __weak NSLayoutConstraint *subtitleTextFieldHeightConstraint; // @synthesize subtitleTextFieldHeightConstraint=_subtitleTextFieldHeightConstraint;
@property __weak NSLayoutConstraint *titleTextFieldHeightConstraint; // @synthesize titleTextFieldHeightConstraint=_titleTextFieldHeightConstraint;
@property(nonatomic) unsigned long long maxNumberOfSubtitleLines; // @synthesize maxNumberOfSubtitleLines=_maxNumberOfSubtitleLines;
@property(nonatomic) unsigned long long maxNumberOfTitleLines; // @synthesize maxNumberOfTitleLines=_maxNumberOfTitleLines;
- (void)setUsesErrorStyleTextColor:(BOOL)arg1;
- (void)setFilterMatchString:(id)arg1;
- (void)setTitleFilterMatchRange:(struct _NSRange)arg1;
- (struct _NSRange)titleFilterMatchRange;
@property struct _NSRange titleRangeToEnsureIsVisible;
@property BOOL titleShouldReplaceNewlinesWithVisibleCharacter;
- (void)awakeFromNib;

@end

